---
title: "respiration_model"
output: pdf_document
date: "2024-01-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r check measured respiration data only}
library("amerifluxr")
library(Kendall)
library(xts)
library(lubridate)
library(tidyverse)
library(Rbeast)
library(suncalc)
library(ggpubr)
library(ppcor)
library(car)
library(lutz)
library(REddyProc)
rm(list=ls())
#
# get site information such as long and lat
name_site <- 'US-IB2'
sites <- amf_site_info()
site  <- sites %>% filter(SITE_ID==name_site)
long_site  <- site$LOCATION_LONG
lat_site   <- site$LOCATION_LAT
elevation  <- site$LOCATION_ELEV  
#
tz <- tz_offset(as.Date("2000-01-01"), tz_lookup_coords(lat=lat_site, lon=long_site, method='accurate'))
# put the exact time zone
if (tz$utc_offset_h > 0) {
  tz_site  <- paste0('GMT-', tz$utc_offset_h)
} else {
  tz_site  <- paste0('GMT+', -tz$utc_offset_h)
}
#
#
files <- list.files(pattern="zip", full.names = T)
# create a time series for this site
a <- amf_read_base(files[grepl(name_site, files)], parse_timestamp=TRUE, unzip = T)
#
ac <- a[, 1:7]
ac$ndays <- 365                         # number of days in a year
ac$ndays[leap_year(ac$YEAR)] <- 366
# add time column
a$time <- a$YEAR + a$DOY/ac$ndays
#
# get sunrise and sunset time
sunrise_set <- getSunlightTimes(
    date = seq.Date(as.Date(a$TIMESTAMP[1]), as.Date(a$TIMESTAMP[nrow(a)]), by = 1),       # Date format: YYYY-MM-DD
    keep = c("sunrise", "sunset"),
    lat = lat_site,
    lon = long_site,
    tz  = tz_site
  )
#
# Force the time zone to GMT in order to be consistent with the date format in AmeriFlux database
sunrise_set$sunrise <- as.POSIXct(as.character(sunrise_set$sunrise), tz='GMT')
sunrise_set$sunset <- as.POSIXct(as.character(sunrise_set$sunset), tz='GMT')
#
# determine: day-time or night-time
ac$DATE <- as.Date(ac$TIMESTAMP) 
ac <- ac %>% left_join(sunrise_set, by = c('DATE' = 'date'))
#
dt <- a$TIMESTAMP[2] - a$TIMESTAMP[1]
#
# another way to calculate this
a$daytime <- a$TIMESTAMP + dt/2.0 >= ac$sunrise & a$TIMESTAMP - dt/2.0 <= ac$sunset
#
#
######################Obtain exactly measured night respiration######################################
#
plot(a$FC)                
plot(a$TA)                 
plot(a$TS_1_1_1)          
plot(a$SWC_1_1_1)        
#
plot(a$SW_IN)           
plot(a$RH)
plot(a$USTAR)
#
######################################decide which variables to use#######################################
# modify the dataframe ac
if ("ndays" %in% colnames(ac)) {
  ac = subset(ac, select=-c(ndays, DATE, lat, lon, sunrise, sunset))
}
ac$NEE <- a$FC              
ac$TA  <- a$TA
ac$TS  <- a$TS_1_1_1      
ac$SWC <- a$SWC_1_1_1
ac$daytime <- a$daytime
ac$SW_IN   <- a$SW_IN
ac$USTAR   <- a$USTAR
ac$RH      <- a$RH
#########################################################################################################
##########################################do Ustar filtering#############################################
NEE_yearly <- ac %>% group_by(DOY) %>% summarise(NEE=mean(NEE, na.rm=T), TS=mean(TS, na.rm=T))   
plot(NEE_yearly$DOY, NEE_yearly$NEE)
#
# I will use the mean of the first three values, and the mean of the last three values
tmp    <- NEE_yearly %>% filter(NEE < min(NEE_yearly$NEE, na.rm=T) * 0.2)
#
# Start and end of growing season
gStart <- as.integer(mean(tmp$DOY[7])) - 4
gEnd   <- as.integer(mean(tmp$DOY[(nrow(tmp)-6)])) + 4
gStart
gEnd
#
# temperature range of growing season
tStart = as.integer(quantile(tmp$TS, c(0.025), na.rm=T) * 10) + 1     #
tEnd   = as.integer(quantile(tmp$TS, c(0.975), na.rm=T) * 10) + 1     #
#
# Create seasonStarts with two columns: one is day, and the other is year!
years  <- unique(ac$YEAR)
seasonStarts <- data.frame(DOY = rep(c(gStart, gEnd), length(years)), YEAR=rep(years, each=2))
#
# create the data frame
ac_u       <- data.frame(DateTime = ymd_hm(a$TIMESTAMP_END))   
ac_u$NEE   <- ac$NEE
ac_u$Rg    <- ac$SW_IN
ac_u$Tair  <- ac$TA
ac_u$Ustar <- ac$USTAR
ac_u$rH    <- ac$RH
#
ac_u$VPD <- fCalcVPDfromRHandTair(ac_u$rH, ac_u$Tair)

EProc    <- sEddyProc$new(name_site, ac_u, c('NEE', 'Rg', 'Tair', 'VPD', 'Ustar'))
EProc$sSetLocationInfo(LatDeg = lat_site, LongDeg = long_site, TimeZoneHour = tz$utc_offset_h)
# 
ac_u$season <- usCreateSeasonFactorYdayYear(
  ac_u$DateTime - 15*60, starts = seasonStarts)  # it sets back 15 min. 
uStarTh <- EProc$sEstUstarThold(seasonFactor = ac_u$season)
#
EProc$sMDSGapFillAfterUstar('NEE', FillAll = FALSE, isVerbose = FALSE)
ac$NEE_uStar_f <- EProc$sExportResults()$NEE_uStar_f
#
ac_u <- ac_u %>% left_join(uStarTh[,3:4], by="season")
ac$uStarTh <- ac_u$uStar
#
#########################################end with Ustar filtering#######################################
# 
a_measure     <- ac %>% filter(!is.na(NEE) & !is.na(TS) & !is.na(SWC) & !is.na(USTAR)) %>% filter(USTAR >= uStarTh)
# 
a_measure_night <- a_measure %>% filter(!daytime)
# 
for (i in years) {
  a_measure_night_year <- a_measure_night %>% filter(YEAR==i)
  # check length of gaps and do a distribution
  if (nrow(a_measure_night_year) > 1) {
    gap <- as.integer(a_measure_night_year$TIMESTAMP[2:nrow(a_measure_night_year)] - a_measure_night_year$TIMESTAMP[1:(nrow(a_measure_night_year)-1)])
    plot(a_measure_night_year$TS, a_measure_night_year$NEE, main=as.character(i), xlim=c(-10, 40), ylim=c(-10, 40))
    # check air temperature and soil temperature relationship
    plot(a_measure_night_year$TA, a_measure_night_year$TS, main=as.character(i), xlim=c(-10, 40), ylim=c(-5, 40))
    # see gaps each year
    plot(a_measure_night_year$TIMESTAMP, a_measure_night_year$NEE, main=as.character(i), xlim=c(as.POSIXct(paste0(i, "-01-01 00:00:00")), as.POSIXct(paste0(i, "-12-31 00:00:00"))))
  } else {
    print(i)
  }
}
# remove years with big gap  
a_measure_night_complete <- a_measure_night %>% filter(!YEAR %in% c(2004, 2014, 2017))
#
a_measure_night_complete <- a_measure_night_complete %>% dplyr::select(c(YEAR, MONTH, DAY, DOY, HOUR, MINUTE, NEE, TA, TS, SWC))

# what I really need to use is the two datasets: a_measure_night_complete, ac
iStart = a_measure_night_complete$YEAR[1]
iEnd   = a_measure_night_complete$YEAR[nrow(a_measure_night_complete)]

# gap-fill TA, TS, NEE to get annual growing-season TA, TS, and NEE. 
T_gf <- ac %>% group_by(DOY, HOUR, MINUTE) %>% summarise(TA_gf=mean(TA, na.rm=T), TS_gf=mean(TS, na.rm=T), NEE_gf=mean(NEE_uStar_f, na.rm=T)) 
if (!"TA_gf" %in% colnames(ac)) {
  ac   <- ac %>% left_join(T_gf, by=c("DOY", "HOUR", "MINUTE"))
}
# gap-fill using the day, hour, and minutes of a year  
if (sum(is.na(ac$TA)) > 0) {
  ac$TA[is.na(ac$TA)] <- ac$TA_gf[is.na(ac$TA)]
}
if (sum(is.na(ac$TS)) > 0) {
  ac$TS[is.na(ac$TS)] <- ac$TS_gf[is.na(ac$TS)]
}
if (sum(is.na(ac$NEE_uStar_f)) > 0) {
  ac$NEE_uStar_f[is.na(ac$NEE_uStar_f)] <- ac$NEE_gf[is.na(ac$NEE_uStar_f)]
}

# save gap-filled data
write.csv(ac[, c("YEAR", "MONTH", "DAY", "DOY", "HOUR", "MINUTE", "NEE_uStar_f", "TA", "TS")], file=paste0(name_site, '_gap_filled_data.csv'), row.names = FALSE)
# save non-gap-filled data
write.csv(a_measure_night_complete, file=paste0(name_site, '_non_gap_filled_data.csv'), row.names = FALSE)
#
```


```{r try the five models first, fig.width=6, fig.hight=5}
library(gslnls)
library(caret)
library(performance)
#
# put this to a_measure_night_complete;
data <- a_measure_night_complete %>% filter(YEAR >= iStart)
#----------------------------------------------------------------------------------------------------------------------
# check data quality first
plot(data$TS, data$NEE)
plot(data$DOY, data$NEE)
#-----------------------------------------------------------------------------------------------------------------------
# model 1: linear exponential
frmu   <- NEE ~ C_pool * exp(alpha * TS) * SWC / (Hs + SWC)    # in this formula: C_pool, alpha, beta, and Hs are unknown parameters.
stprm  <- c(C_pool=1, alpha=0.1, Hs = 20)
df_accurate <- data.frame(NEE=data$NEE, TS=data$TS, SWC=data$SWC)
#
mod1 <- gsl_nls(fn=frmu, data=df_accurate, start=stprm)
summary(mod1)
NEE_pred <- predict(mod1, newdata=df_accurate)
plot(df_accurate$TS, df_accurate$NEE)
# check performance
postResample(pred=NEE_pred, obs=df_accurate$NEE)
performance_aicc(mod1)
#  RMSE     Rsquared     MAE      aicc
#  1.4759117 0.6275146 0.8646112
#-----------------------------------------------------------------------------------------------------------------------
# model 2: quadratic exponential (!the best model!)
frmu   <- NEE ~ C_pool * exp(alpha * TS + beta*TS^2) * SWC / (Hs + SWC)     
stprm  <- c(C_pool=1, alpha=0.1, beta=-0.01, Hs = 20)
df_accurate <- data.frame(NEE=data$NEE, TS=data$TS, SWC=data$SWC)
mod2 <- gsl_nls(fn=frmu, data=df_accurate, start=stprm)
summary(mod2)
NEE_pred <- predict(mod2, newdata=df_accurate)
plot(df_accurate$TS, df_accurate$NEE)
# check performance
postResample(pred=NEE_pred, obs=df_accurate$NEE)
performance_aicc(mod2)
#    RMSE Rsquared      MAE     aicc
# 1.4410967 0.6430417 0.8003121             
# 
# The best parameter values
# C_pool  2.803e-01  8.119e-03   34.53   <2e-16 ***
# alpha   2.216e-01  2.885e-03   76.81   <2e-16 ***
# beta   -3.331e-03  7.878e-05  -42.28   <2e-16 ***
# Hs      1.214e+01  6.594e-01   18.40   <2e-16 ***
#
#-----------------------------------------------------------------------------------------------------------------------
# model 3: parabolic equations
frmu   <- NEE ~ (C_pool + alpha * (TS - Topt)^2)  * SWC / (Hs + SWC)
stprm  <- c(C_pool = 5, alpha = 0.1, Topt = 0, Hs = 20)
df_accurate <- data.frame(NEE=data$NEE, TS=data$TS, SWC=data$SWC)
#
mod3 <- gsl_nls(fn=frmu, data=df_accurate, start=stprm)
summary(mod3)
NEE_pred <- predict(mod3, newdata=df_accurate)
plot(df_accurate$TS, NEE_pred)
# check performance
postResample(pred=NEE_pred, obs=df_accurate$NEE)
performance_aicc(mod3)
#    RMSE    Rsquared   MAE         AICc
# 1.4451896 0.6409142 0.8067702 

#-----------------------------------------------------------------------------------------------------------------------
# model 4: Arrhenius (the worst model)
frmu   <- NEE ~ C_pool * exp(- alpha / 8.3144598 / (TS + 273.15)) * SWC / (Hs + SWC)    
stprm  <- c(C_pool = 0.5, alpha = 20, Hs = 20)
df_accurate <- data.frame(NEE=data$NEE, TS=data$TS, SWC=data$SWC)
#
mod4 <- gsl_nls(fn=frmu, data=df_accurate, start=stprm)
summary(mod4)
NEE_pred <- predict(mod4, newdata=df_accurate)
plot(df_accurate$TS, NEE_pred)
# check performance
postResample(pred=NEE_pred, obs=df_accurate$NEE)
performance_aicc(mod4)
#    RMSE    Rsquared      MAE      AICc
# 1.9362024 0.5691679 1.4015856
#-----------------------------------------------------------------------------------------------------------------------
# model 5: Modified Arrhenius  (better than the last; almost the same)
frmu   <- NEE ~ C_pool * exp(- alpha * (1/(15+46.02) - 1/(TS+46.02))) * SWC / (Hs + SWC)    
stprm  <- c(C_pool = 0.5, alpha = 20, Hs = 20)
df_accurate <- data.frame(NEE=data$NEE, TS=data$TS, SWC=data$SWC)
#
mod5 <- gsl_nls(fn=frmu, data=df_accurate, start=stprm)
summary(mod5)
NEE_pred <- predict(mod5, newdata=df_accurate)
plot(df_accurate$TS, NEE_pred)
# check performance
postResample(pred=NEE_pred, obs=df_accurate$NEE)
performance_aicc(mod5)
#    RMSE Rsquared      MAE   AICc
# 1.4489977 0.6391955 0.8167987

# mod2 is the best; 

```


```{r how about predicting for each year using the best model}
library(gslnls)
# using all the data to select the best model type; prepare for the data
NEE_annual <- ac %>% filter(YEAR >= iStart & YEAR <= iEnd) %>% group_by(YEAR) %>% summarise(TA=mean(TA, na.rm=T), TS=mean(TS, na.rm=T), SWC=mean(SWC, na.rm=T)) 
NEE_grow   <- ac %>% filter(DOY >= gStart & DOY <= gEnd) %>% filter(YEAR >= iStart & YEAR <= iEnd) %>% group_by(YEAR) %>% summarise(TA=mean(TA, na.rm=T), TS=mean(TS, na.rm=T), SWC=mean(SWC, na.rm=T)) 
#
#
coef <- data.frame(year=double(), C_pool=double(), alpha=double(), beta=double())
perf <- data.frame(year=double(), RMSE=double(), Rsquared=double(), MAE=double())
#
for (i in iStart:iEnd) {     
  data <- a_measure_night_complete %>% filter(YEAR==i)   #
  if (nrow(data) <= 10) {
    next
  }
  print(i)
  #-----------------------------------------------------------------------------------------------------------------------
  # model 2: quadratic exponential (!the best model!)
  Hs = 1.214e+01                  # This value is from the best model
  frmu   <- NEE ~ C_pool * exp(exp(alpha) * TS + beta*TS^2) * SWC / (SWC+Hs)
  stprm  <- c(C_pool=20, alpha=-1, beta=-0.01)  
  df_accurate <- data.frame(NEE=data$NEE, TS=data$TS, SWC=data$SWC)      
  #
  mod2 <- gsl_nls(fn=frmu, data=df_accurate, start=stprm)
  summary(mod2)
  NEE_pred <- predict(mod2, newdata=df_accurate)
  plot(df_accurate$TS, df_accurate$NEE, main=i)
  lines(df_accurate$TS, NEE_pred)
  # check performance
  performance_aicc(mod2)
  coef[i-iStart+1,] <- c(i, coefficients(mod2)[1], exp(coefficients(mod2)[2]), coefficients(mod2)[3])
  perf[i-iStart+1,] <- c(i, postResample(pred=NEE_pred, obs=df_accurate$NEE))  
}
#
```

```{r test if there is thermal acclimation}
# strength of thermal acclimation
# T-ER curves of different years
result <- data.frame(TS=double(), NEE=double(), year=integer())
TS    = seq(0, 26, 0.1)
nTS   = length(TS)
nyear = nrow(coef)
for (i in 1:nyear) {
  #
  result[((i-1)*nTS+1):(i*nTS), 3] <- i + iStart - 1
  result[((i-1)*nTS+1):(i*nTS), 1] <- TS
  #
  alpha  = coef$alpha[i]
  beta   = coef$beta[i]
  C_pool = coef$C_pool[i]
  Hs = 1.214e+01                 # This value is from the best model
  SWC = mean(ac$SWC, na.rm=TRUE)
  result[((i-1)*nTS+1):(i*nTS), 2] <- C_pool * exp(alpha * TS + beta * TS * TS) * SWC / (SWC+Hs) 
}

#
ggplot(result, aes(x=TS, y=NEE, col=as.factor(year))) +
  geom_line() +
  geom_point() +
  geom_vline(xintercept = tStart/10) +
  geom_vline(xintercept = tEnd/10)

#
result_row <- spread(result, key=year, value=NEE)
#
result_row_avg <- rowMeans(result_row[, 2:(nyear+1)], na.rm=T)
RRavg_GW       <- log(result_row[tStart:tEnd, 2:(nyear+1)] / result_row_avg[tStart:tEnd])
#
# use weighted average for each column/year
RRavg_GW       <- (RRavg_GW * result_row_avg[tStart:tEnd]) / sum(result_row_avg[tStart:tEnd])
RRavg_GW       <- colSums(RRavg_GW)
#
cor.test(RRavg_GW, NEE_grow$TS)    # p-value = 0.01317
#
# no correlation
df <- data.frame(TS=NEE_grow$TS, alpha = RRavg_GW)
ggplot(df, aes(x=TS, y=alpha)) + 
  geom_point() +
  geom_smooth(method = lm) +
  stat_cor(color='green') + 
  labs(x='Mean soil temperature (C)', y='normalized night respiration under growth temperature')
# linear regression
summary(lm(data=df, alpha~TS))    # slope = -0.04211; This is thermal response strength of this site. 
#
outcome <- list(site_ID=name_site, tStart=tStart/10, tEnd=tEnd/10, annual_TS_grow=NEE_grow[,c('YEAR', 'TS')], annual_TS_ER_curves=result_row)
saveRDS(outcome, file=paste0(name_site, '_data_estimate_acclimation.RDS'))
#
#
```
