---
title: "future_respiration"
output: pdf_document
date: "2024-06-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Please note that this function requests observed nighttime temperature~respiration data for each study site to run. The data is very large and will be placed in an online repository. Here, I only put such data for one site US-IB2 as an example. 


```{r estimate current and future respiration}
library(tidyverse)
library(gslnls)
library(caret)
library(performance)
library(zoo)
rm(list=ls())
options(na.action = "na.omit")
# read data used for this module 
#
acclimation <- read.csv("acclimation_data_clear.csv")
#
Tmin_month <- read.csv('Tmin_month_ssp245_wc.csv')
acclimation     <- acclimation %>% left_join(Tmin_month, by='site_ID')
#
# add 6 column about respiration
acclimation$TS_TA   <- 0            # conversion between TS and TA
acclimation$TSmin_c <- 0            # monthly min soil temperature change
acclimation$TSmin_c_gs <- 0         # gs: growing season
acclimation$NEE_night_mod_p <- 0
acclimation$NEE_night_mod_f <- 0
acclimation$NEE_night_mod_fa <- 0
#
files  <- list.files(pattern = '_ac.RDS$', full.names = TRUE)
# workflow
# air and soil temperature patterns
for (i in 1:length(files)) {
  name_site <- substring(files[i], nchar(files[i])-12, nchar(files[i])-7)
  print(paste0(i, name_site))
  #
  iacclimation <- which(acclimation$site_ID==name_site)
  #
  ac <- readRDS(files[i])
  #
  # use only the years with qualified data
  outcome <- readRDS(paste0("./", name_site, '_outcome.RDS'))
  good_years <- as.integer(colnames(outcome$result)[!is.na(outcome$result[1,])])
  good_years <- good_years[!is.na(good_years)]
  # recalculate TS_TA relationship using TA threshold
  if (name_site!='GF-Guy') {
    tmp <- ac %>% filter(TA > 0)   # only use the data with TA > 0C; use another range to calculate the coefficient
    outcome$TS_TA <- summary(lm(data=tmp, TS~TA))$coefficients[2,1]
  }
  #
  night_pattern <- ac %>% filter(YEAR %in% good_years & !daytime) %>% group_by(DOY, HOUR, MINUTE, MONTH) %>% summarise(TAp=mean(TA, na.rm=T), TSp=mean(TS, na.rm=T), SWC=mean(SWC, na.rm=T), NEEo=mean(NEE, na.rm=T))
  # remove duplicate rows
  night_pattern  <- night_pattern[!duplicated(night_pattern[,c('DOY', 'HOUR', 'MINUTE')]), ]
  # deal with occasional TA missing cases
  if (sum(is.na(night_pattern$TAp)) > 0) {
    night_pattern$TAp <- na.approx(night_pattern$TAp)
  }
  # deal with occasional TS missing cases
  if (sum(is.na(night_pattern$TSp)) > 0) {
    mod_lm <- lm(data=night_pattern, TSp ~ TAp)
    TSp_pred <- predict(mod_lm, night_pattern)
    night_pattern$TSp[is.na(night_pattern$TSp)] <- TSp_pred[is.na(night_pattern$TSp)]
  }
  #
  temp_change   <- data.frame(MONTH=1:12, TAmnc=as.numeric(acclimation[iacclimation, which(colnames(acclimation) %in% (paste0('Tmin', 1:12)))]))
  #
  night_pattern <- night_pattern %>% left_join(temp_change, by="MONTH")
  #
  night_pattern$TAf <- night_pattern$TAp + night_pattern$TAmnc
  night_pattern$TSf <- night_pattern$TSp + night_pattern$TAmnc * outcome$TS_TA
  #
  data <- readRDS(paste0("./", name_site, '_nightNEE.RDS'))
  if (acclimation$SWC_use[acclimation$site_ID==name_site]=='YES') {
    # fit the temperature respiration model
    frmu   <- NEE ~ C_pool * exp(alpha * TS + beta*TS^2)  * SWC / (Hs + SWC)     # in this formula: C_pool, alpha, beta, and Hs are unclear parameters. I know Cpool and Hs should be positive;
    if (name_site=='ZA-Kru') {
      stprm  <- c(C_pool=10, alpha=0.1, beta=-0.01, Hs = 100)
    } else if (name_site=='GF-Guy') {
      stprm  <- c(C_pool=1, alpha=0.1, beta=-0.001, Hs = 20)
    } else {
      stprm  <- c(C_pool=1, alpha=0.1, beta=-0.01, Hs = 20) # 
    }
    df_accurate <- data.frame(NEE=data$NEE, TS=data$TS, SWC=data$SWC)
    mod2 <- gsl_nls(fn=frmu, data=df_accurate, start=stprm)
    summary(mod2)
    NEE_pred <- predict(mod2, newdata=df_accurate)
    plot(df_accurate$TS, df_accurate$NEE)
    # check performance
    postResample(pred=NEE_pred, obs=df_accurate$NEE)
    # predict current night respiration
    # firstly, deal with occasional SWC missing cases using linear regression
    if (sum(is.na(night_pattern$SWC)) > 0) {
      night_pattern$time <- night_pattern$DOY + night_pattern$HOUR / 24 + night_pattern$MINUTE / 60 / 24
      # re-order the data
      night_pattern <- night_pattern %>% arrange(time)
      # then linear interpolation
      night_pattern$SWC.appr <- na.approx(night_pattern$SWC, night_pattern$time, na.rm = FALSE)
      # dealing with missing head and end data
      num_min <- min(which(!is.na(night_pattern$SWC.appr)))
      num_max <- max(which(!is.na(night_pattern$SWC.appr)))
      if (num_min > 1) {
        night_pattern$SWC.appr[1:(num_min-1)] <- night_pattern$SWC.appr[num_min]
      }
      if (num_max < nrow(night_pattern)) {
        night_pattern$SWC.appr[(num_max+1):nrow(night_pattern)] <- night_pattern$SWC.appr[num_max]
      }
      night_pattern$SWC <- night_pattern$SWC.appr
      night_pattern$SWC.appr <- NULL
    }
    #
    df_present <- data.frame(TS=night_pattern$TSp, SWC= night_pattern$SWC)
    night_pattern$NEEp <- predict(mod2, newdata=df_present)
    #
    # predict for future respiration
    df_future <- data.frame(TS=night_pattern$TSf, SWC= night_pattern$SWC)
    night_pattern$NEEf <- predict(mod2, newdata=df_future)    
  } else {
    frmu   <- NEE ~ C_pool * exp(alpha * TS + beta*TS^2)
    stprm  <- c(C_pool=1, alpha=0.1, beta=-0.01) # 
    df_accurate <- data.frame(NEE=data$NEE, TS=data$TS)
    mod2 <- gsl_nls(fn=frmu, data=df_accurate, start=stprm)
    summary(mod2)
    NEE_pred <- predict(mod2, newdata=df_accurate)
    plot(df_accurate$TS, df_accurate$NEE)
    # check performance
    postResample(pred=NEE_pred, obs=df_accurate$NEE)
    # predict current night respiration
    #
    df_present <- data.frame(TS=night_pattern$TSp)
    night_pattern$NEEp <- predict(mod2, newdata=df_present)
    #
    # predict for future respiration
    df_future <- data.frame(TS=night_pattern$TSf)
    night_pattern$NEEf <- predict(mod2, newdata=df_future)     
  }
  # get the required values
  acclimation$TS_TA[iacclimation] <- outcome$TS_TA
  acclimation$TSmin_c[iacclimation] <- mean(temp_change$TAmnc) * outcome$TS_TA
  #
  # NEE during growing season only
  acclimation$NEE_night_mod_p[iacclimation]  <- mean(night_pattern$NEEp[night_pattern$DOY >= outcome$gStart & night_pattern$DOY <= outcome$gEnd])
  acclimation$NEE_night_mod_f[iacclimation]  <- mean(night_pattern$NEEf[night_pattern$DOY >= outcome$gStart & night_pattern$DOY <= outcome$gEnd])
  NEE_gs <- mean(night_pattern$NEEf[night_pattern$DOY >= outcome$gStart & night_pattern$DOY <= outcome$gEnd]) 
  acclimation$TSmin_c_gs[iacclimation] <- mean(night_pattern$TAmnc[night_pattern$DOY >= outcome$gStart & night_pattern$DOY <= outcome$gEnd]) * outcome$TS_TA
  acclimation$NEE_night_mod_fa[iacclimation] <- NEE_gs * exp(acclimation$r3avg[iacclimation] * acclimation$TSmin_c_gs[iacclimation])
}
#
write.csv(acclimation, file='acclimation_data_future.csv', row.names = F)
#
```
