---
title: "plot_figure_thermal_acclimation"
output: pdf_document
date: "2024-06-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
library(terra)
library(tidyterra)
library(egg)
library(viridis)
library(RColorBrewer)
library(grid)
library(cowplot)
#
```


```{r compare thermal acclimation with or without water, fig.width=8, fig.height=9}
rm(list=ls())
#
dir  <- '/Users/jw2946/Documents/stability_project/manuscripts/plot/'
data <- read.csv(file.path(dir, 'acclimation_strength_compare_nowater.csv'))   # the first 54 rows are useful for this purpose. 
#
acclimation <- read.csv(file.path(dir, 'acclimation_data_final.csv'))
acclimation.use <- acclimation[, c("site_ID", "r3avg", "r3avg_p", "IGBP", "Climate_class")]
colnames(acclimation.use)[5] <- 'Climate'
# acclimation.use$r3avg_nw   <- acclimation.use$r3avg
# acclimation.use$r3avg_p_nw <- acclimation.use$r3avg_p
#
data <- left_join(data, acclimation.use, by='site_ID')
#
cor.test(data$r3avg, data$r3avg_nw)
#
data <- data %>% mutate(climate_class = dplyr::recode(Climate,
                                              'Am'='Humid tropical',
                                              'Bsh'='Semiarid',            # 'Arid and semi-arid',
                                              'Bsk'='Semiarid',            # 'Arid and semi-arid',
                                              'Bwk'='Arid desert',         # 'Arid and semi-arid',
                                              'Cfa'='Humid subtropical',            # 'Temperate humid',
                                              'Cfb'='Humid subtropical',            # 'Temperate humid',
                                              'Csa'='Hot-summer Mediterranean',            # 'Mediterranean',
                                              'Csb'='Warm-summer Mediterranean',           # 'Mediterranean',
                                              'Dfa'='Humid continental',            # 'Humid continental',
                                              'Dfb'='Humid continental',            # 'Humid continental',
                                              'Dfc'='Humid continental',            # 'Subarctic',
                                              'Dfd'='Humid continental',            # 'Subarctic',
                                              'Dwc'='Humid continental',            # 'Subarctic',
                                              'ET' ='Tundra'))             # 'Tundra')) 
# points, 1:1 line, set vegetation class
p1 <- ggplot(data=data, aes(x=r3avg, y=r3avg_nw, shape=climate_class, color=climate_class)) +
  geom_point(size=3) +
  geom_abline(intercept = 0, slope=1, color="black", linetype = "dashed", size = 0.5) +
  annotate("text", x = -0.1, y = 0.06, label = expression(italic('R')^2~' = 0.68, '~italic('p')~' < 0.01'), size = 4, color = "black", fontface = "bold") +
  labs(x=expression('TAS'[ER]~ "estimates controlling for soil water's effects on respiration"), y=expression('TAS'[ER]~ "estimates not controlling for soil water's effects "), shape='Climate class', color='Climate class', tag='a') + #
  scale_x_continuous(expand = c(0, 0), lim=c(-0.35, 0.1)) +
  scale_y_continuous(expand = c(0, 0), lim=c(-0.35, 0.1)) +
  scale_color_manual(values = c("Humid tropical"='#1EAFC8', "Arid desert" = "#fe9695", "Semiarid" = "#f5a403", "Humid subtropical" = "#66ff33", "Hot-summer Mediterranean" = "#fffe05", 'Warm-summer Mediterranean'="#c7c702", 'Humid continental'="#38c8ff", 'Tundra' ="#b2b2b2")) +  
  scale_shape_manual(values = c("Humid tropical"=1, "Arid desert" = 15, "Semiarid" = 12, "Humid subtropical" = 13, "Hot-summer Mediterranean" = 17, 'Warm-summer Mediterranean'=6, 'Humid continental'=19, 'Tundra'=8)) +
  theme_bw() +
  theme(legend.position = c(0.2, 0.75),   # Place legend inside the plot at (x, y)
        legend.background = element_rect(fill = alpha('white', 0.6)))
p1
#
#
# subdata <- data %>% filter(climate_class %in% c('Humid continental', 'Tundra', 'Humid tropical'))   # 'Humid subtropical', 
# t.test(subdata$r3avg, subdata$r3avg_nw, paired=TRUE)
# # no difference in 'Humid continental', 'Tundra'; p-value = 0.3891
# #
# subdata <- data %>% filter(climate_class %in% c('Semiarid'))
# t.test(subdata$r3avg, subdata$r3avg_nw, paired=TRUE)
# #
# subdata <- data %>% filter(climate_class %in% c('Humid subtropical'))
# t.test(subdata$r3avg, subdata$r3avg_nw, paired=TRUE)
# #
# subdata <- data %>% filter(climate_class %in% c('Warm-summer Mediterranean','Hot-summer Mediterranean'))  # 
# t.test(subdata$r3avg, subdata$r3avg_nw, paired=TRUE)
#

# data$climate_class <- factor(data$climate_class, labels = c('Humid tropical', 'Arid desert', 'Semiarid', 'Humid subtropical', 'Hot-summer Mediterranean', 'Warm-summer Mediterranean', 'Humid continental'))
data_comp <- tidyr::gather(data[, c('climate_class', 'r3avg', 'r3avg_nw')], key = "key", value = "value", -climate_class)
p2 <- ggplot(data=data_comp, aes(x=climate_class, y=value, fill=key)) +
#  geom_bar(position = "dodge", stat="identity", width=0.75) +  
  geom_boxplot(outlier.shape = NA) +
  theme_bw() +
  scale_fill_discrete(labels=c('Control for soil water', 'No control for soil water')) +
  labs(x='Climate class', y=expression('TAS'[ER]~ '(°C'^{-1}~')'), fill=expression('Methods for estimating TAS'[ER]), tag='b') +
  theme(axis.text.x = element_text(angle = 10, hjust = 0.6, vjust=0.7)) +
  theme(legend.position = c(0.17, 0.25),   # Place legend inside the plot at (x, y)
        legend.background = element_rect(fill = alpha('white', 0.6))) +
  theme(panel.grid.minor = element_blank())
p2
#
plot_grid(p1, p2, nrow=2, ncol=1, rel_heights = c(1.5, 1))
#
ggsave('soil_water_effects_on_TAS_estimates.png', dpi=600)
#

```

```{r correlation plot of independent variable, fig.width=8, fig.height=8}
library(Hmisc)
library(corrplot)
rm(list=ls())
#
data <- read.csv(file='/Users/jw2946/Documents/stability_project/manuscripts/plot/acclimation_data_final.csv')
#
# the 12 predictor variables are divided into a few categories
# geographic and climatic, soil properties, vegetation and ecosystem properties
rcorr_results <- rcorr(as.matrix(data[, c('ELEV', 'MAP', 'MATA', 'SSTA', 'RDTA', 'IATA', 'soc_mix', 'ph_mix', 'NDVI', 'EVI', 'Lai', "Gpp")]))   # 'nitrogen', 
cor_matrix <- rcorr_results$r
p_matrix <- rcorr_results$P

# Print correlation matrix
print(cor_matrix)

# Print p-value matrix
print(p_matrix)

# plot the correlation figure
# this is the reference page
# https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html
#
data.use           <- data[, c('ELEV', 'MAP', 'MATA', 'SSTA', 'RDTA', 'IATA', 'soc_mix', 'ph_mix', 'NDVI', 'EVI', 'Lai', "Gpp")]
colnames(data.use) <- c("ELEV", 'MAP', 'MAT', 'SST', 'DRT', 'IAT', 'SOC', 'SpH', 'NDVI', 'EVI', 'LAI', 'GPP')
#
M=cor(data.use)
testRes = cor.mtest(data.use, conf.level = 0.99)
#
png(filename = "variable_correlation.png", width = 800, height = 600)
plot <- corrplot(M, p.mat = testRes$p, sig.level = 0.01, method = 'circle', insig='blank',
         diag = FALSE)
p1 <- plot$corrPos
plot %>% corrRect(c(1,2, 7,9,12))
text(p1$x, p1$y, round(p1$corr, 2))
dev.off()
#
# ggsave('variable_correlation.png', dpi=600)
# , type = 'upper'

```

```{r illustration of this method, fig.width=6, fig.height=9}
library(ggrepel)
rm(list=ls())
#
options(na.action = na.omit)
acclimation.strength <- data.frame(site_ID=character(), strgth=double(), strgth_p=double(), 
                                   r3=double(), r3_p=double(), r3avg=double(), r3avg_p=double()) 
data_dir <- "/Users/jw2946/Documents/stability_project/RespiarationData/"
files <- list.files(data_dir, pattern='_outcome.RDS', full.names = T) 
  # i = 49     # US-Kon
  i = 43       # US-IB2 
  print(i)
  outcome.in <- readRDS(files[i])
  #
  acclimation.strength[i, 1] <- outcome.in$site_ID
  tStart   <- outcome.in$tStart
  tEnd     <- outcome.in$tEnd
  NEE_grow <- outcome.in$NEE_grow
  nyear    <- nrow(NEE_grow)
  #
  # average respiration over the growing season
  result_row <- outcome.in$result
  # plot the curve first
  # plot T-ER curve for each year
  # remove na columns
  result <- result_row
  result[, is.na(result[1,])] <- NULL
  # number of years
  result$control <- rowMeans(result[,2:ncol(result)])
  result <- gather(result, key='year', value='NEE', -TS)
  # step 1
p1 <-  ggplot(result, aes(x=TS, y=NEE, col=year, size=year)) +
  geom_line() +
  scale_size_manual(values = c(rep(0.5,12), 1)) +                       # 11
  scale_color_manual(values = c("#f6756c", "#e18a00", "#bd9b00", "#8cab00", "#24b501", "#02bf70", "#00bfa9", "#00badb", "#00adfc", "#8c94ff", "#d575fd", "#f962dd", "#0E2F44")) +
  labs(x='Soil temperature (°C)', y=expression('Night R'[E]~' (µmol CO'[2]~ ' m'^{-2}~ ' s'^{-1}~')'), col='Year', size='Year', tag='a') +
  lims(x=c(0, 30)) +
  theme_bw() +
  theme(legend.position = c(0.2, 0.57),
        legend.background = element_rect(fill = alpha('white', 0.1))) +
        guides(col = guide_legend(ncol = 2), size = guide_legend(ncol = 2))
  # step 2
  # select a typical year to show how to calculate acclimation ratio
p2 <-  result %>% filter(year %in% c('2006', 'control')) %>%           # 2017
  ggplot(aes(x=TS, y=NEE, col=year, size=year)) +
  geom_line() +
  scale_size_manual(values = c(0.5, 1)) + 
  scale_color_manual(values = c("#e18a00", "#0E2F44")) +  
  labs(x='Soil temperature (°C)', y=expression('Night R'[E]~' (µmol CO'[2]~ ' m'^{-2}~ ' s'^{-1}~')'), col='Year', size='Year', tag='b') +
  lims(x=c(0, 30)) +
  theme_bw()  +
  geom_vline(xintercept = tStart/10, linetype = "dashed") +
  geom_vline(xintercept = tEnd/10, linetype = "dashed") +
  theme(legend.position = c(0.2, 0.75),
        legend.background = element_rect(fill = alpha('white', 0.6)))
  #
  # step 3
result_row_avg <- rowMeans(result_row[, 2:(nyear+1)], na.rm=T)
  RRavg_GW       <- result_row[tStart:tEnd, 2:(nyear+1)] / result_row_avg[tStart:tEnd]
  RRavg_GW       <- colMeans(RRavg_GW)
  #
  # calculate acclimation strength by three methods
df <- data.frame(TS=NEE_grow$TS, SWC=NEE_grow$SWC, alpha_ln_avg=log(RRavg_GW), year=NEE_grow$YEAR)
  #
p3 <-  ggplot(df, aes(x=TS, y=alpha_ln_avg)) + 
  geom_point() +
  geom_text_repel(aes(label=year), size=3) +
  geom_smooth(method = lm) +
  stat_cor(color='green', label.x = 19.5, label.y = 0.15) +
  labs(x='Annual mean growing-season soil temperature (°C)', y='-ln(mean acclimation ratio) (unitless)', tag='c') +
  theme_bw()
  #
  summary(lm(data=df, alpha_ln_avg~TS))$coefficients[2,c(1,4)]    

plot_grid(p1, p2, p3, nrow=3, ncol=1)
ggsave('TAS_calculation_example.png', dpi=600)

```

```{r figure 1, fig.width=8, fig.height=7.37}
rm(list=ls())
acclimation <- read.csv('acclimation_data_final.csv')

# figure1: global distribution of the sites; I should give colors to these points for these acclimation strength; 
mundi <- vect(rnaturalearthdata::coastline110)
# mundi <- crop(mundi,ext(c(-180,180,-60,90)))
 colors <- c("#053061", "#2166AC", "#4393C3", "#92C5DE", "#D1E5F0", "#F7F7F7", "#FDDBC7" ,"#F4A582")      # brewer.pal(11, "RdBu")  "PiYG"
# values <- c(0, 0.2, 0.4, 0.55, 0.7, 0.85, 0.925, 1)           # c(0, 0.17, 0.34, 0.51, 0.68, 0.85, 0.925, 1)
# breaks <- c(-0.3, -0.2, -0.1, 0, 0.06)

#
p1 <- ggplot() +
  geom_spatvector(data = mundi, linewidth = .2) +
  geom_hline(yintercept=0, linetype = "dotted", colour = "grey") + 
  geom_point(data=acclimation, aes(x=LONG, y=LAT, fill=r3avg), shape = 21, size = 2, stroke = 0.5, color='black') +
#  scale_fill_gradientn(colors = colors, values=values, breaks = breaks, limits = c(-0.34, 0.06), na.value = "transparent") +
#  scale_fill_binned(type = "viridis") +  #
  scale_fill_stepsn(breaks=c(-0.3, -0.2, -0.1, 0), colors = c("#0D1E34", "#053061", "#4393C3", "#D1E5F0", "#E4003A"), limits = c(-0.36, 0.1)) +  # limits = c(-0.34, 0.06)
  # , oob = scales::squish
  labs(x='Longitude', y='Latitude', fill=expression(italic('TAS')[ER]~ '(°C'^{-1}~')'), tag='c') +
  coord_sf(expand=FALSE, xlim = c(-180, 180), ylim = c(-50, 90)) + 
  theme_bw() +
  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.border = element_rect(colour = "black")) +
  theme(legend.position = c(0.1, 0.31),
        legend.background = element_rect(fill = alpha('white', 1.0))) +
  guides(fill = guide_colorbar(barwidth = 1, barheight = 5.5))
p1
#
#
acclimation$compensate <- cut(acclimation$r3avg, breaks=c(-0.4, -0.3, -0.2, -0.1, 0, 0.1), labels=seq(-0.3, 0.1, 0.1))
p2 <- ggplot(data=acclimation, aes(x=r3avg)) +
  geom_vline(xintercept=0, linetype = "dotted", colour = "grey") +
  geom_histogram(aes(fill=compensate), color='black', bins=20, breaks=seq(from=-0.36, to=0.1, by=0.02)) +  # 
#  scale_fill_gradientn(colors = colors, values=values, breaks = breaks, limits = c(-0.34, 0.06), na.value = "transparent") +
  labs(x=expression(italic('TAS')[ER]~ '(°C'^{-1}~')'), y='Number of sites', tag='d') + 
  scale_y_continuous(lim=c(0, 13), breaks=seq(from=0, to=13, by=3)) + 
  scale_fill_manual(values = c("#0D1E34", "#053061", "#4393C3", "#D1E5F0", "#eb686c")) + 
  theme_classic() +
  theme(legend.position = "none")
# it is better that the two figures share the same color; put figure (b) into the (a) plot. 
#
p2_grob <- ggplotGrob(p2)
#
p1_combined <- p1 + 
  annotation_custom(
    grob = p2_grob,
    xmin=45, xmax=180,
    ymin=0, ymax=90)
print(p1_combined)

# create data for compensating and enhancing thermal acclimation
Ts <- seq(from=0, to=20, by=1)
ERavg <- 0.9 * exp(0.2 * Ts - 0.0037 * Ts * Ts)
ER1 <- 1.0 * exp(0.18 * Ts - 0.0035 * Ts * Ts)
ER2 <- 0.8 * exp(0.225 * Ts - 0.0040 * Ts * Ts)

data_compensate <- data.frame(Ts=Ts, ERavg=ERavg, ERwarm=ER1, ERcool=ER2)
data_compensate <- data_compensate %>% gather(key='Year', value='ER', -Ts)

# compensating  y = 13,  "'Compensating thermal acclimation \n (negative ' * italic('TAS')[ER]~')'", parse=TRUE, 
# expression("Compensating thermal acclimation \n (negative"~italic('TAS')[ER]~")")
p3 <- ggplot(data = data_compensate, aes(x=Ts, y=ER, color=Year)) +
  geom_line() +
  annotate("text", x = 9, y = 14, label = "Compensating thermal acclimation", size = 4, color = "blue", fontface = "bold") +
  labs(x='Soil temperature (°C)', y=expression('Nighttime R'[E]~' (µmol CO'[2]~ ' m'^{-2}~ ' s'^{-1}~')'), tag='a') +
  scale_color_manual(values = c("black", "#0F67B1", "#FF7F3E"), labels = c('An average year', 'A cool year',  'A warm year')) +  
  theme_classic() +
  theme(legend.position = c(0.3, 0.6),
        legend.background = element_rect(fill = alpha('white', 0.6)))
p3

# enhancing: y = 13, "'Enhancing thermal acclimation \n (positive ' * italic('TAS')[ER]~')'" , parse=TRUE
#
p4 <- ggplot(data = data_compensate, aes(x=Ts, y=ER, color=Year)) +
  geom_line() +
  annotate("text", x = 9, y = 14, label = "Enhancing thermal acclimation", size = 4, color = "#E4003A", fontface = "bold") +
  labs(x='Soil temperature (°C)', y=expression('Nighttime R'[E]~' (µmol CO'[2]~ ' m'^{-2}~ ' s'^{-1}~')'), tag='b') +
  scale_color_manual(values = c("black", "#FF7F3E", "#0F67B1"), labels = c('An average year',  'A warm year', 'A cool year')) +  
  theme_classic() +
  theme(legend.position = c(0.3, 0.6),
        legend.background = element_rect(fill = alpha('white', 0.6)))
p4
#
p34 <- plot_grid(p3, p4, ncol=2, nrow=1)
#
# combine the four figures
plot_grid(p34, p1_combined, nrow=2, ncol=1, align=c('hv'), bg='white')
ggsave('Fig1_study_site.png', dpi=600)
#
# problems to figure out: how to breakout colors

```

```{r code to plot different climate classes}
# Load required package
library(plotbiomes) 

# Create a data frame with temperature and precipitation values 
climate_data <- data.frame(
  temp_c = c(10, 25, -5, 15, 5), 
  precip_cm = c(100, 500, 200, 150, 50)
)

# Classify biomes using the 'get_biome' function
# climate_data$biome <- get_biome(climate_data$temp_c, climate_data$precip_cm) 
# # View the results
# print(climate_data) 

#
acclimation <- read.csv('acclimation_data_final.csv')
whittaker_base_plot() +
  geom_point(data=acclimation, aes(x=MAT, y=MAP/10, color=r3avg), size=5)

##This is not a good way to show our data; many points are clustered. 


```


```{r figure 2, ranges of calculated TAS, fig.width=4.6, fig.height=3.5}
library(ggsignif)
# figure 2
#
rm(list=ls())
acclimation <- read.csv('acclimation_data_final.csv')
rs_field    <- read.csv('r3_field.csv')
#
t.test(acclimation$r3avg, acclimation$r3avg[acclimation$significant])
# p-value = 0.0003882
# 
t.test(rs_field$r3[rs_field$result=='YES'], acclimation$r3avg[acclimation$significant])
# t = 0.6894, df = 71.385, p-value = 0.4928
# means: -0.1154954, -0.1301248 (ours)
#
df <- data.frame(value = c(acclimation$r3avg, acclimation$r3avg[acclimation$significant], 
                           rs_field$r3[rs_field$result=='YES']))
#
df$cat <- c(rep('This study (all)', nrow(acclimation)), 
            rep('This study (p < 0.1)', length(acclimation$r3avg[acclimation$significant])), 
            rep('Literature (significant)', length(rs_field$r3[rs_field$result=='YES']))) 
#
df$Respiration <- c(rep('ecosystem', nrow(acclimation)), 
                  rep('ecosystem', length(acclimation$r3avg[acclimation$significant])), 
                  rs_field$respiration[rs_field$result=='YES'])
#
#
# my question here is how to name these values
df$cat <- factor(df$cat, levels=c('This study (all)', 'This study (p < 0.1)', 'Literature (significant)'))
ggplot(data=df, aes(x=cat, y=value)) +
  geom_boxplot(outlier.shape = NA, width=0.1) +
  geom_violin(alpha=0) +
  geom_jitter(alpha=0.8, width=0.4, aes(color=Respiration, shape=Respiration)) +
  geom_signif(comparisons = list(c('This study (all)', 'This study (p < 0.1)'), c('This study (p < 0.1)', 'Literature (significant)')), 
              map_signif_level=TRUE, color='black', tip_length = 0.02) +
  scale_x_discrete(labels = c('This study (all)', expression('This study ('~italic(p)~' < 0.1)'), 'Literature (significant)')) +
  labs(x='', y=expression(italic('TAS')~' of different respirations (°C'^{-1}~')')) +
#  scale_color_manual(values = c("This study (all)" = "#92C5DE", "This study (p < 0.1)" = "#2166AC", "Literature (significant)" = "black")) +
  scale_shape_manual(values = c("ecosystem"=16, "leaf"=17, "root"=3, "soil"=15),
                     labels = c("ecosystem" = "Ecosystem", "leaf" = "Leaf", "root" = "Root", "soil" = "Soil")) +
  scale_color_manual(values = c("ecosystem"="skyblue", "leaf"="darkgreen", "root"="darkgoldenrod", "soil"="black"),
                     labels = c("ecosystem" = "Ecosystem", "leaf" = "Leaf", "root" = "Root", "soil" = "Soil")) +
  lims(y=c(-0.51, 0.35)) +
  theme_bw() +
  theme(legend.position = c(0.5, 0.9),          ##legend.position = "top",         # 
        legend.background = element_rect(fill = "transparent", color = NA),  # Transparent background
        legend.box.background = element_rect(fill = "transparent", color = NA)) +
  guides(color = guide_legend(nrow = 1)) +
  guides(shape = guide_legend(nrow = 1)) +
  theme(panel.grid.major = element_blank(), # Remove major grid lines
        panel.grid.minor = element_blank()) 

ggsave('Fig2_estimated_TAS.png', dpi=600)
#
# expression('This study ('~italic(p)~' < 0.05)')

# "#053061", "#2166AC", "#4393C3", "#92C5DE", "#D1E5F0"

```


```{r figure 3 driver of thermal acclimation, fig.width=8.2, fig.height=8}
library(vip)
#
rm(list=ls())
#
########################################
# relative importance figure
vis <- read.csv('VarImp.csv')
vis[, 2:5] <- vis[, 2:5] * 100
vis$var <- factor(vis$var, levels=c('mat', 'ph', 'lai', 'ele'))
#
f1 <- ggplot(vis, aes(y=med500, x=var, fill=var)) +
  geom_bar(stat = "identity", width=0.6) +
  geom_errorbar(aes(ymin=low050, ymax=high950), width=0.2) + 
  coord_flip() +
  labs(x='', y='Relative importance (%)', tag='b') +
  scale_y_continuous(expand = c(0, 0), lim=c(0, 42)) +
  scale_fill_manual(values = c('#f8766d', '#619cff', '#00bb38', '#ab6b51')) +
  scale_x_discrete(labels = c("mat" = "Annual air temperature", "ph" = "pH in soil water", "lai" = "Annual leaf area index", 'ele'='Elevation')) +
  theme_bw() +
  theme(legend.position = "none") +
  theme(panel.grid.major = element_blank(),  # Remove major grid lines
        panel.grid.minor = element_blank()) 
f1

#####sensitivity of climate class#####
acclimation <- read.csv(file='/Users/jw2946/Documents/stability_project/manuscripts/plot/acclimation_data_final.csv')
#
acclimation.use <- acclimation[, c("r3avg", "IGBP", "Climate_class", "Lai", "MATA", "ELEV", "ph_mix")]
#
anova_test <- aov(r3avg ~ Climate_class, data=acclimation.use)
summary(anova_test)
#
colnames(acclimation.use) <- c("r3avg", "IGBP", "KCC", "LAI", "MAT", "ELEV", "pH")
acclimation.class <- acclimation.use %>% mutate(climate_class = dplyr::recode(KCC,
                                              'Am'='Tropical',                                
                                              'Bsh'='Semiarid',            # 'Arid and semi-arid',
                                              'Bsk'='Semiarid',            # 'Arid and semi-arid',
                                              'Bwk'='Arid desert',         # 'Arid and semi-arid',
                                              'Cfa'='Humid subtropical',            # 'Temperate humid',
                                              'Cfb'='Humid subtropical',            # 'Temperate humid',
                                              'Csa'='Hot-summer Mediterranean',            # 'Mediterranean',
                                              'Csb'='Warm-summer Mediterranean',           # 'Mediterranean',
                                              'Dfa'='Humid continental',            # 'Humid continental',
                                              'Dfb'='Humid continental',            # 'Humid continental',
                                              'Dfc'='Humid continental',            # 'Subarctic',
                                              'Dfd'='Humid continental',            # 'Subarctic',
                                              'Dwc'='Humid continental',            # 'Subarctic',
                                              'ET' ='Tundra'))           # 'Tundra'))           
#
# I need to test if these groups are significant. anova test (p = 0.0365)
acclimation.class$climate_class <- factor(acclimation.class$climate_class, levels=c('Tropical', 'Semiarid', 'Arid desert', 'Humid subtropical', 'Hot-summer Mediterranean', 'Warm-summer Mediterranean', 'Humid continental', 'Tundra'))
f2 <- ggplot(data=acclimation.class, aes(x=KCC, y=r3avg, color=climate_class)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(alpha=0.2) +
  labs(x='The Köppen climate class', y=expression(italic('TAS'[ER])~ '(°C'^{-1}~')'), color=NULL, tag='a') +
  # scale_color_manual(values = c("Bwk" = "#fe9695", "Bsh" = "#f5a403", "Bsk" = "#ffdb63", "Cfa" = "#c6ff4e", "Cfb" = "#66ff33", "Csa" = "#fffe05", 'Csb'="#c7c702",
  #                              'Dfa'="#01ffff", 'Dfb'="#38c8ff", 'Dfc'="#007f7d", 'Dfd'="#00455f", 'Dwc'="#4d52b5", 'ET' ="#b2b2b2")) +
  # a different color scheme
  scale_color_manual(values = c("Tropical" = "#1EAFC8", "Arid desert" = "#fe9695", "Semiarid" = "#f5a403", "Humid subtropical" = "#66ff33", "Hot-summer Mediterranean" = "#fffe05", 'Warm-summer Mediterranean'="#c7c702", 'Humid continental'="#38c8ff", 'Tundra' ="#b2b2b2")) +
  scale_y_continuous(expand = c(0, 0), lim=c(-0.36, 0.2)) +  
  #
  theme_bw() +
  theme(legend.position = c(0.5, 0.9),
        legend.text = element_text(size = 8),
        legend.key.size = unit(0.4, "cm"),
        legend.background = element_rect(fill = "transparent", color = NA),  # Transparent background
        legend.box.background = element_rect(fill = "transparent", color = NA)) +
  guides(color = guide_legend(nrow = 3)) +
  theme(panel.grid.major = element_blank(), # Remove major grid lines
        panel.grid.minor = element_blank())
 f2
 
# Anova test
anova_test <- aov(r3avg ~ KCC, data=acclimation.use)
summary(anova_test)   # p = 0.077 (*)
# how to test if mean values of different groups are different.

###########################make response curves (two lines for each plot)############
partial <- read.csv(file='/Users/jw2946/Documents/stability_project/manuscripts/plot/partial_plot.csv')
f3 <- partial %>% filter(var %in% c('elev')) %>% ggplot(aes(x=x, y=y)) +
  geom_line(col='#ab6b51') +
  geom_ribbon(aes(ymin=y050, ymax=y950), fill='#ab6b51', alpha=0.1) +
  scale_x_continuous(expand = c(0, 0), lim=c(0, 3050)) +  
#  scale_y_continuous(expand = c(0, 0), lim=c(-0.15, 0)) + 
  labs(x='Elevation (m)', y=expression(italic('TAS'[ER])~ '(°C'^{-1}~')'), tag='c') +
  theme_classic()
f3

f4 <- partial %>% filter(var %in% c('lai')) %>% ggplot(aes(x=x, y=y)) +
  geom_line(col='#00bb38') +
  geom_ribbon(aes(ymin=y050, ymax=y950), fill='#00bb38', alpha=0.1) +
  scale_x_continuous(expand = c(0, 0)) +  
  # scale_y_continuous(expand = c(0, 0), lim=c(-0.15, 0)) + 
  labs(x=expression('Mean annual leaf area index (m'^2~'m'^{-2}~')'), y=expression(italic('TAS'[ER])~ '(°C'^{-1}~')'), tag='d') +
  theme_classic()
f4

f5 <- partial %>% filter(var %in% c('ph')) %>% ggplot(aes(x=x, y=y)) +
  geom_line(col='#619cff') +
  geom_ribbon(aes(ymin=y050, ymax=y950), fill='#619cff', alpha=0.1) +
  scale_x_continuous(expand = c(0, 0)) +  
  # scale_y_continuous(expand = c(0, 0), lim=c(-0.15, 0)) + 
  labs(x='pH in soil water', y=expression(italic('TAS'[ER])~ '(°C'^{-1}~')'), tag='e') +
  theme_classic()
f5

f6 <- partial %>% filter(var %in% c('mat')) %>% ggplot(aes(x=x, y=y)) +
  geom_line(col='#f8766d') +
  geom_ribbon(aes(ymin=y050, ymax=y950), fill='#f8766d', alpha=0.1) +
  scale_x_continuous(expand = c(0, 0), breaks=seq(-5, 25, 5)) +  
  # scale_y_continuous(expand = c(0, 0), lim=c(-0.15, 0)) + 
  labs(x='Mean annual air temperature (°C)', y=expression(italic('TAS'[ER])~ '(°C'^{-1}~')'), tag='f') +
  theme_classic()
f6
#
f1_2 <- plot_grid(f2, f1, nrow=1, ncol=2, rel_widths = c(0.6, 0.4))
f3_6 <- plot_grid(f3, f4, f5, f6, nrow=2, ncol=2)
plot_grid(f1_2, f3_6, nrow=2, ncol=1, rel_heights = c(0.4, 0.6))
# 
ggsave('Fig3_driver_analysis.png', dpi=600)

```

```{r TAS varies vegetation groups and driver analysis from data only, fig.width=8.2, fig.height=8}
#
acclimation <- read.csv(file='/Users/jw2946/Documents/stability_project/manuscripts/plot/acclimation_data_final.csv')
#
acclimation.use <- acclimation[, c("r3avg", "IGBP", "Climate_class", "Lai", "MATA", "ELEV", "ph_mix", "significant")]
#
anova_test <- aov(r3avg ~ IGBP, data=acclimation.use)
summary(anova_test)   # p = 0.19
#
p1 <- ggplot(data=acclimation.use, aes(x=IGBP, y=r3avg, color=IGBP)) +
  geom_boxplot(outlier.shape = NA, width=0.5) +
  geom_jitter(alpha=0.2) +
  labs(x='The IGBP land cover class', y=expression(italic('TAS'[ER])~ '(°C'^{-1}~')'), color=NULL, tag='a') +
  scale_color_discrete(labels = c("ENF" = "Evergreen Needleleaf Forests", "DBF" = "Deciduous Broadleaf Forests", "GRA" = "Grasslands", "WSA" = "Woody Savannas", "WET" = "Wetlands", 'MF'="Mixed Forests", 'OSH'="Open Shrublands", 'SAV' ="Savannas", 'CSH' ="Closed Shrublands", "EBF" = "Evergreen Broadleaf Forests")) +  
  scale_y_continuous(expand = c(0, 0), lim=c(-0.36, 0.2)) +  
  #
  theme_bw() +
  theme(legend.position = c(0.5, 0.9),
        legend.text = element_text(size = 10),
        legend.key.size = unit(0.4, "cm"),
        legend.background = element_rect(fill = "transparent", color = NA),  # Transparent background
        legend.box.background = element_rect(fill = "transparent", color = NA)) +
  guides(color = guide_legend(nrow = 3)) +
  theme(panel.grid.major = element_blank(), # Remove major grid lines
        panel.grid.minor = element_blank())
p1
################################################################################
#######driver analysis from data only
p2 <- ggplot(data=acclimation.use, aes(x=ELEV, y=r3avg)) +
  geom_point(aes(shape=significant)) +
  geom_smooth(method='lm') +
  stat_cor(color='royalblue') + 
  labs(x='Elevation (m)', y=expression(italic('TAS'[ER])~ '(°C'^{-1}~')'), shape=expression("Significant "~italic("TAS")), tag='b') +
  ylim(c(-0.36, 0.15)) +
  theme_classic() +
  theme(legend.position = c(0.75, 0.85),
        legend.text = element_text(size = 10),
        legend.key.size = unit(0.4, "cm"),
        legend.background = element_rect(fill = "transparent"),  # Transparent background
        legend.box.background = element_rect(fill = "transparent")) +
  guides(color = guide_legend(nrow = 2))
p2
##################
p3 <- acclimation.use %>% filter(!Climate_class %in% c('Bsh', 'Csb', 'ET', 'Csa', 'Bwk', 'Bsk')) %>%  # , 'Am'
  ggplot(aes(x=Lai, y=r3avg)) +
  geom_point(aes(shape=significant)) +
  geom_smooth(method='lm') +
  stat_cor(color='royalblue') + 
  labs(x=expression('Mean annual leaf area index (m'^2~'m'^{-2}~')'), y=expression(italic('TAS'[ER])~ '(°C'^{-1}~')'), shape=expression("Significant "~italic("TAS")), tag='c') +
  ylim(c(-0.36, 0.15)) +
  theme_classic() +
    theme(legend.position = c(0.75, 0.85),
          legend.text = element_text(size = 10),
          legend.key.size = unit(0.4, "cm"),
          legend.background = element_rect(fill = "transparent"),  # Transparent background
          legend.box.background = element_rect(fill = "transparent")) +
    guides(color = guide_legend(nrow = 2))
p3
##################
p2_3 <- plot_grid(p2, p3, nrow=1, ncol=2 )
#
plot_grid(p1, p2_3, nrow=2, ncol=1)
# 
ggsave('driver_TAS_SI.png', dpi=600)

```


```{r temperature-ecosystem respiration relationships, generate data, use once only}
library(gslnls)
library(caret)
#
rm(list=ls())
options(na.action = na.omit)
acclimation <- read.csv('acclimation_data_final.csv')
data_dir <- "/Users/jw2946/Documents/stability_project/RespiarationData/ALL10122024/"
files    <- list.files(data_dir, pattern='_nightNEE.RDS', full.names = T)
# remove the sites not used. all the sites are used!
# files %in% paste0(data_dir, '/', acclimation$site_ID, '_nightNEE.RDS')
#
TS_ER_curves <- data.frame(TS=double(), ER=double(), site_ID=character())
df_check     <- data.frame(site_ID=character(), R2 = double(), sensitivity = double())
# I need 50 points for every study site. 
#
for (i in 1:length(files)) {
  #
  # i = 45
  print(i)
  name_site <- substring(files[i], nchar(files[i])-18, nchar(files[i])-13)
  TS_ER_curves[((i-1)*50+1) : (i*50), 3] <- name_site
  df_check[i, 1] <- name_site
  #
  ac  <- readRDS(files[i])
  TS1 <- as.numeric(quantile(ac$TS, prob=0.025, na.rm=TRUE))
  TS2 <- as.numeric(quantile(ac$TS, prob=0.975, na.rm=TRUE))
  TS_ER_curves[((i-1)*50+1) : (i*50), 1] <- seq(from=TS1, to=TS2, length.out=50)
  #
  # to see if there is enough soil water data
  if (sum(!is.na(ac$SWC)) > 8000) {
    # enough data to include soil moisture here
    print(paste0(name_site, ' use_water'))
    frmu   <- NEE ~ C_pool * exp(alpha * TS + beta*TS^2) * SWC / (Hs + SWC)
    if (name_site=='ZA-Kru') {
      stprm  <- c(C_pool=10, alpha=0.1, beta=-0.01, Hs = 100)
    } else if (name_site=='GF-Guy') {
      stprm  <- c(C_pool=1, alpha=0.1, beta=-0.001, Hs = 20)
    } else {
      stprm  <- c(C_pool=1, alpha=0.1, beta=-0.01, Hs = 20) # 
    }
    df_accurate <- data.frame(NEE=ac$NEE, TS=ac$TS, SWC=ac$SWC)
    mod2 <- gsl_nls(fn=frmu, data=df_accurate, start=stprm)
    summary(mod2)
    NEE_pred <- predict(mod2, newdata=df_accurate)
    # plot(NEE_pred, df_accurate$NEE)
    # check performance
    print(postResample(pred=NEE_pred, obs=df_accurate$NEE))
    #
    df_pred <- data.frame(TS=seq(from=TS1, to=TS2, length.out=50), SWC=rep(mean(ac$SWC, na.rm=T), 50))
    TS_ER_curves[((i-1)*50+1) : (i*50), 2] <- predict(mod2, newdata=df_pred)
    #
  } else {
    frmu   <- NEE ~ C_pool * exp(alpha * TS + beta*TS^2)
    stprm  <- c(C_pool=1, alpha=0.1, beta=-0.01)
    df_accurate <- data.frame(NEE=ac$NEE, TS=ac$TS)
    mod2 <- gsl_nls(fn=frmu, data=df_accurate, start=stprm)
    summary(mod2)
    NEE_pred <- predict(mod2, newdata=df_accurate)
 #   plot(NEE_pred, df_accurate$NEE)
    # check performance
    print(postResample(pred=NEE_pred, obs=df_accurate$NEE))
    #
    df_pred <- data.frame(TS=seq(from=TS1, to=TS2, length.out=50))
    TS_ER_curves[((i-1)*50+1) : (i*50), 2] <- predict(mod2, newdata=df_pred)    
  }
  #
  df_check[i, 2] <- cor(NEE_pred, df_accurate$NEE, use = "complete.obs") ^2
  #
  # calculate sensitivity
  # get growing season temperature
  outcomes <- readRDS(paste0(data_dir, name_site, '_outcome.RDS'))
  tStart <- outcomes$tStart / 10
  tEnd <- outcomes$tEnd / 10
#  tmpt <- TS_ER_curves[((i-1)*50+1) : (i*50), 2] * (coefficients(mod2)[2] + coefficients(mod2)[3] * 2 * df_pred$TS)
  tmpt <- (coefficients(mod2)[2] + coefficients(mod2)[3] * 2 * df_pred$TS)
  df_check[i, 3] <- mean(tmpt[which(df_pred$TS >= tStart & df_pred$TS <= tEnd)])
  #
}
df_check <- left_join(df_check, acclimation[, c('site_ID', 'r3avg', 'MATA', 'NEE', 'Climate_class')], by='site_ID')
#
TS_ER_curves <- TS_ER_curves %>% left_join(acclimation[, c('site_ID', 'Climate_class')], by='site_ID')
colnames(TS_ER_curves)[4] <- 'KCC'
# write out the data
write.csv(TS_ER_curves, 'TS_ER_relation_allsites.csv')


```

```{r plot the temperature-respiration curves, fig.width=8, fig.height=12}
TS_ER_curves <- read.csv('TS_ER_relation_allsites.csv')
#
p1 <- ggplot(data=TS_ER_curves, aes(x=TS, y=ER, color=site_ID)) +
  geom_line() +
  annotate("text", x = 10, y = 15, label = "All eddy-covariance study sites", size = 3, fontface = "bold") +      # color=""
  labs(x='Soil temperature (°C)', y=expression('Night R'[E]~' (µmol CO'[2]~ ' m'^{-2}~ ' s'^{-1}~')'), tag='a') + 
  theme_classic() +
  theme(legend.position = "none")
p1
#
p2 <- TS_ER_curves %>% filter(KCC %in% c("Cfa", "Cfb", "Am")) %>% ggplot(aes(x=TS, y=ER, color=site_ID)) +
  geom_line() +
  annotate("text", x = 13, y = 15, label = "Sites in humid tropical, subtropical climate", size = 3, fontface = "bold") +      # color=""
  labs(x='Soil temperature (°C)', y=expression('Nighttime R'[E]~' (µmol CO'[2]~ ' m'^{-2}~ ' s'^{-1}~')'), color= 'Site ID', tag='b') +  
  theme_classic() +
  theme(legend.position = c(0.2, 0.65),
        legend.text = element_text(size = 6),  # Adjust legend text font size
        legend.title = element_text(size = 8),
        legend.spacing.y = unit(0.25, "cm"),
        legend.spacing.x = unit(0.0, "cm"),
        legend.key.height = unit(0.25, "cm"),       # Reduce height of legend keys
        legend.background = element_rect(fill = alpha('white', 0.1))) +
  guides(col = guide_legend(ncol = 2), size = guide_legend(ncol = 2))
p2
#
p3 <- TS_ER_curves %>% filter(KCC %in% c("Bsk", "Bsh")) %>% ggplot(aes(x=TS, y=ER, color=site_ID)) +
  geom_line() +
  annotate("text", x = 15, y = 6, label = "Sites in semi-arid climate", size = 3, fontface = "bold") +      # color=""
  labs(x='Soil temperature (°C)', y=expression('Nighttime R'[E]~' (µmol CO'[2]~ ' m'^{-2}~ ' s'^{-1}~')'), color= 'Site ID', tag='c') +  
  theme_classic() +
  theme(legend.position = c(0.15, 0.65),
        legend.text = element_text(size = 6),  # Adjust legend text font size
        legend.title = element_text(size = 8),
        legend.spacing.y = unit(0.25, "cm"),
        legend.spacing.x = unit(0.0, "cm"),
        legend.key.height = unit(0.25, "cm"),       # Reduce height of legend keys
        legend.background = element_rect(fill = alpha('white', 0.1)))
p3
#
p4 <- TS_ER_curves %>% filter(KCC %in% c("Bwk")) %>% ggplot(aes(x=TS, y=ER, color=site_ID)) +
  geom_line() +
  annotate("text", x = 15, y = 6, label = "Sites in arid desert climate", size = 3, fontface = "bold") +      # color=""
  labs(x='Soil temperature (°C)', y=expression('Nighttime R'[E]~' (µmol CO'[2]~ ' m'^{-2}~ ' s'^{-1}~')'), color= 'Site ID', tag='d') +  
  theme_classic() +
  theme(legend.position = c(0.15, 0.6),
        legend.text = element_text(size = 6),  # Adjust legend text font size
        legend.title = element_text(size = 8),
        legend.spacing.y = unit(0.25, "cm"),
        legend.spacing.x = unit(0.0, "cm"),
        legend.key.height = unit(0.25, "cm"),       # Reduce height of legend keys
        legend.background = element_rect(fill = alpha('white', 0.1)))
p4
#
p5 <- TS_ER_curves %>% filter(KCC %in% c("Csa")) %>% ggplot(aes(x=TS, y=ER, color=site_ID)) +
  geom_line() +
  annotate("text", x = 15, y = 10, label = "Sites in hot-summer Mediterranean climate", size = 3, fontface = "bold") +      # color=""
  labs(x='Soil temperature (°C)', y=expression('Nighttime R'[E]~' (µmol CO'[2]~ ' m'^{-2}~ ' s'^{-1}~')'), color= 'Site ID', tag='e') +  
  theme_classic() +
  theme(legend.position = c(0.15, 0.6),
        legend.text = element_text(size = 6),  # Adjust legend text font size
        legend.title = element_text(size = 8),
        legend.spacing.y = unit(0.25, "cm"),
        legend.spacing.x = unit(0.0, "cm"),
        legend.key.height = unit(0.25, "cm"),       # Reduce height of legend keys
        legend.background = element_rect(fill = alpha('white', 0.1)))
p5
#
p6 <- TS_ER_curves %>% filter(KCC %in% c("Csb")) %>% ggplot(aes(x=TS, y=ER, color=site_ID)) +
  geom_line() +
  annotate("text", x = 12, y = 10, label = "Sites in warm-summer Mediterranean climate", size = 3, fontface = "bold") +      # color=""
  labs(x='Soil temperature (°C)', y=expression('Nighttime R'[E]~' (µmol CO'[2]~ ' m'^{-2}~ ' s'^{-1}~')'), color= 'Site ID', tag='f') +  
  theme_classic() +
  theme(legend.position = c(0.15, 0.6),
        legend.text = element_text(size = 6),  # Adjust legend text font size
        legend.title = element_text(size = 8),
        legend.spacing.y = unit(0.25, "cm"),
        legend.spacing.x = unit(0.0, "cm"),
        legend.key.height = unit(0.25, "cm"),       # Reduce height of legend keys
        legend.background = element_rect(fill = alpha('white', 0.1)))
p6
#
p7 <- TS_ER_curves %>% filter(KCC %in% c("Dfa", "Dfb", "Dfc", "Dfd", "Dwc")) %>% ggplot(aes(x=TS, y=ER, color=site_ID)) +
  geom_line() +
  annotate("text", x = 18, y = 10, label = "Sites in humid continental climate", size = 3, fontface = "bold") +      # color=""
  labs(x='Soil temperature (°C)', y=expression('Nighttime R'[E]~' (µmol CO'[2]~ ' m'^{-2}~ ' s'^{-1}~')'), color= 'Site ID', tag='g') +  
  lims(x=c(-15, 33)) +
  theme_classic() +
  theme(legend.position = c(0.17, 0.6),
        legend.text = element_text(size = 5),  # Adjust legend text font size
        legend.title = element_text(size = 8),
        legend.spacing.y = unit(0.25, "cm"),
        legend.spacing.x = unit(0.0, "cm"),
        legend.key.height = unit(0.25, "cm"),       # Reduce height of legend keys
        legend.background = element_rect(fill = alpha('white', 0.1))) +
  guides(col = guide_legend(ncol = 2), size = guide_legend(ncol = 2))
p7
#
p8 <- TS_ER_curves %>% filter(KCC %in% c("ET")) %>% ggplot(aes(x=TS, y=ER, color=site_ID)) +
  geom_line() +
  annotate("text", x = 0, y = 4, label = "Sites in tundra climate", size = 3, fontface = "bold") +      # color=""
  labs(x='Soil temperature (°C)', y=expression('Nighttime R'[E]~' (µmol CO'[2]~ ' m'^{-2}~ ' s'^{-1}~')'), color= 'Site ID', tag='h') +  
  theme_classic() +
  theme(legend.position = c(0.2, 0.8),
        legend.text = element_text(size = 6),  # Adjust legend text font size
        legend.title = element_text(size = 8),
        legend.spacing.y = unit(0.25, "cm"),
        legend.spacing.x = unit(0.0, "cm"),
        legend.key.height = unit(0.25, "cm"),       # Reduce height of legend keys
        legend.background = element_rect(fill = alpha('white', 0.1)))
p8

plot_grid(p1, p2, p3, p4, p5, p6, p7, p8, ncol=2, nrow=4, align='hv')
# theme(
#     legend.text = element_text(size = 12),  # Adjust legend text font size
#     legend.title = element_text(size = 14))
ggsave('soil_temperature_repiration_curves.png', dpi=600)

```


```{r new figure for respiration mitigation by climate classes-three cases, fig.width=8, fig.height=11}
library(ggsignif)
#
rm(list=ls())
options(na.action = na.omit)
data.future   <- read.csv('acclimation_data_future_ssp245.csv')
data.future$TAmin_c_gs  <- data.future$TSmin_c_gs / data.future$TS_TA
# group the acclimation's effect by climate class
#
data  <- data.future[, c("site_ID", "IGBP", "NEE_night_mod_p", "NEE_night_mod_f", "NEE_night_mod_fa", "NEE_night_mod_fa05", "NEE_night_mod_fa95", "TAmin_c_gs", "TSmin_c_gs")]
#
# connect to thermal acclimation strength
tas  <- read.csv('acclimation_data_final.csv')
data <- data %>% left_join(tas, by='site_ID')
# add one more column
data$NEE_night_mod_fa50 <- data$NEE_night_mod_fa
# add one column indicating significance
data$sig <- data$r3avg_p < 0.1
#
data$Climate_class <- data.future$Climate_class
#
# do climate reclassification
data$Climate_class[data.future$Climate_class %in% c("Bwk", "Csa")] <- 'arid_hot_med'
data$Climate_class[data.future$Climate_class %in% c("Bsk", "Bsh", "Csb")] <- 'semi_arid_warm_med'
#
data$Climate_class[data.future$Climate_class %in% c("Am", "Cfa", "Cfb", "Dfa", "Dfb", "Dfc", "Dfd", "Dwc")] <- 'humid'
#
# soil temperature for different climate class
data3 <- data %>% group_by(Climate_class) %>% summarise(ta_c_m=mean(TAmin_c_gs), ta_c_sd=sd(TAmin_c_gs),
                                                        ts_c_m=mean(TSmin_c_gs), ts_c_sd=sd(TSmin_c_gs))
#
# plot figures; how to add an error bar on the bar?
data_plot  <- data3 %>% dplyr::select(c("Climate_class", "ta_c_m", "ts_c_m"))   %>% rename("ta_c"="ta_c_m",  "ts_c"="ts_c_m")  %>% gather(key='Scenario', value='Temp_mean', -Climate_class)
data_plot1 <- data3 %>% dplyr::select(c("Climate_class", "ta_c_sd", "ts_c_sd")) %>% rename("ta_c"="ta_c_sd", "ts_c"="ts_c_sd") %>% gather(key='Scenario', value='Temp_sd',   -Climate_class)
# set NA standard deviation to 0
data_plot1[is.na(data_plot1)] <- 0.0
# merge the two data frame
data_plot  <- data_plot %>% left_join(data_plot1, by= c("Climate_class", "Scenario"))
#
data_plot$Climate_class <- factor(data_plot$Climate_class, levels=c('arid_hot_med', 'semi_arid_warm_med', 'humid', 'ET'))
#
dodge <- position_dodge(width = 0.75)
p1 <- ggplot(data=data_plot, aes(x=Climate_class, y=Temp_mean, fill=Scenario)) +
  geom_bar(position = "dodge", stat="identity", width=0.75, color='black', size=0.5) +  # color = "black"
  geom_errorbar(aes(ymin=Temp_mean-Temp_sd, ymax=Temp_mean+Temp_sd), width = 0.25, position = dodge, size=0.3) +
  scale_x_discrete(labels = c("Arid & hot-summer Mediterranean", "Semi-arid & warm-summer Mediterranean", "Humid tropical, subtropical & continental", "Tundra")) + 
  scale_fill_manual(values = c("#ECECEC", "darkgrey"), labels = c("Air temperature", "Topsoil temperature")) +         #"#9473b3", "#845d52"  "#C6E2FF", "darkgrey", #D86F6F
  labs(y='Night temperature rise by 2041-2060 (°C)', x='Aggregated climate class', fill='', tag='a', title='All climates') +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 10, hjust = 0.6, vjust=0.7)) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(legend.position = c(0.25, 0.9),
        legend.text.align = 0,  # Align legend items to the left
        legend.title.align = 0)
p1
#
# Effects on mitigating thermal acclimation
# Do this for all the sites first
# add one more column
data$NEE_night_mod_fa50 <- data$NEE_night_mod_fa
#
###do a correction to future respiration, assuming no overcompensation
threshold <- pmin(data$NEE_night_mod_p, data$NEE_night_mod_f)
data$NEE_night_mod_fa[data$NEE_night_mod_fa < threshold]     <- threshold[data$NEE_night_mod_fa < threshold]
data$NEE_night_mod_fa50[data$NEE_night_mod_fa50 < threshold] <- threshold[data$NEE_night_mod_fa50 < threshold] 
data$NEE_night_mod_fa05[data$NEE_night_mod_fa05 < threshold] <- threshold[data$NEE_night_mod_fa05 < threshold]      # lower limit: stronger acclimation
data$NEE_night_mod_fa95[data$NEE_night_mod_fa95 < threshold] <- threshold[data$NEE_night_mod_fa95 < threshold]      # upper limit: weaker acclimation

# find the sites with significant thermal acclimation
data$NEE_night_mod_fa50[!data$sig] <- data$NEE_night_mod_f[!data$sig]
data$NEE_night_mod_fa05[!data$sig] <- data$NEE_night_mod_f[!data$sig]
data$NEE_night_mod_fa95[!data$sig] <- data$NEE_night_mod_f[!data$sig]

# compensation of significant sites; overcompensation is so common
damp_ratio <- (data$NEE_night_mod_f - data$NEE_night_mod_fa) / (data$NEE_night_mod_f - data$NEE_night_mod_p)
damp_ratio[damp_ratio > 1.0] <- 1
hist(damp_ratio[data$sig])
mean(damp_ratio[data$sig])     # 90 % warming-increased respiration increase

#
damp_ratio95 <- (data$NEE_night_mod_f - data$NEE_night_mod_fa95) / (data$NEE_night_mod_f - data$NEE_night_mod_p)
damp_ratio95[damp_ratio95 > 1.0] <- 1
hist(damp_ratio95[data$sig])
mean(damp_ratio95[data$sig])   # consider the uncertainty: 51 % warming-increased respiration increase

#
# get fractions
data$f_ratio    <- data$NEE_night_mod_f / data$NEE_night_mod_p
data$fa_ratio   <- data$NEE_night_mod_fa / data$NEE_night_mod_p
data$fa50_ratio <- data$NEE_night_mod_fa50 / data$NEE_night_mod_p
data$fa05_ratio <- data$NEE_night_mod_fa05 / data$NEE_night_mod_p
data$fa95_ratio <- data$NEE_night_mod_fa95 / data$NEE_night_mod_p

# box plot
data.plot <- data[,c("Climate_class", "f_ratio", "fa_ratio", "fa50_ratio")]
####whether there is significant difference; no acclimation: 1.104038 %
t.test(data.plot$f_ratio, data.plot$fa_ratio, paired=T)     # p < 0.01; the difference is 0.0482; 46.4% reduction; 
t.test(data.plot$f_ratio, data.plot$fa50_ratio, paired=T)   # p < 0.01; the difference is 0.03;   29.2% reduction; 
#
t.test(data.plot$f_ratio[data.plot$Climate_class=='humid'], data.plot$fa_ratio[data.plot$Climate_class=='humid'], paired=T)    # p < 0.01, no acclimation: 1.116969; the difference is 0.0528; reduce 45.2% 
t.test(data.plot$f_ratio[data.plot$Climate_class=='humid'], data.plot$fa50_ratio[data.plot$Climate_class=='humid'], paired=T)  # p < 0.01, the difference is 0.03044629; reduce: 0.2602938
#
# no acclimation: 1.043347
t.test(data.plot$f_ratio[data.plot$Climate_class=='arid_hot_med'], data.plot$fa_ratio[data.plot$Climate_class=='arid_hot_med'], paired=T)    # p-value = 0.5725, the difference is -0.008457033;
t.test(data.plot$f_ratio[data.plot$Climate_class=='arid_hot_med'], data.plot$fa50_ratio[data.plot$Climate_class=='arid_hot_med'], paired=T)  # p = 1, no difference
#
# no acclimation: 1.056336
t.test(data.plot$f_ratio[data.plot$Climate_class=='semi_arid_warm_med'], data.plot$fa_ratio[data.plot$Climate_class=='semi_arid_warm_med'], paired=T)    # p-value = 0.01761, the difference is 0.04727246; reduce 83.9 %
t.test(data.plot$f_ratio[data.plot$Climate_class=='semi_arid_warm_med'], data.plot$fa50_ratio[data.plot$Climate_class=='semi_arid_warm_med'], paired=T)  # p = 0.04545, 0.03435985; reduce: 60.99%
#
# no acclimation: 1.188172
t.test(data.plot$f_ratio[data.plot$Climate_class=='ET'], data.plot$fa_ratio[data.plot$Climate_class=='ET'], paired=T)    # p-value = 0.09049, the difference is 0.1539641; 81.82 %
t.test(data.plot$f_ratio[data.plot$Climate_class=='ET'], data.plot$fa50_ratio[data.plot$Climate_class=='ET'], paired=T)  # p = 0.2136, 0.1285315; 68.3 %
#

data.plot <- gather(data.plot, key='case', value='ratio', -Climate_class)
p2 <- ggplot(data=data.plot, aes(x=case, y=ratio*100-100)) +
  geom_boxplot(aes(fill=factor(case)), alpha=0.8, outlier.shape = NA, width = 0.6) +
#  geom_jitter(alpha=0.2, width=0.6) +
  geom_signif(y_position = c(29, 34), xmin = c(1, 1), xmax = c(2, 3),
              annotation = c("***", "***"), tip_length = 0.02) +
  geom_hline(yintercept = 0, color = "black", linetype = "dashed", size = 0.2) +  
  scale_x_discrete(labels = c("No acclimation", "Acclimation", "Signifant acclimation only")) + 
  labs(y=expression('Change in night '~italic('R'[E])~' by 2041-2060 (%)'), x='Scenarios for future '~italic('R'[E])~' projection', tag='b', title='All climates') +
  ylim(-10, 37) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 10, hjust = 0.8)) +
  theme(legend.position = "none") +
  theme(plot.title = element_text(hjust = 0.5))
p2

######For sites in different climate classes
p3 <- data.plot %>% filter(Climate_class=="arid_hot_med") %>% ggplot(aes(x=case, y=ratio*100-100)) +
  geom_boxplot(aes(fill=factor(case)), alpha=0.8, outlier.shape = NA, width = 0.6) +
#  geom_jitter() +
  geom_signif(y_position = c(20, 25), xmin = c(1, 1), xmax = c(2, 3),
              annotation = c("NS.", "NS."), tip_length = 0.02) +
  geom_hline(yintercept = 0, color = "black", linetype = "dashed", size = 0.2) +  
  scale_x_discrete(labels = c("No acclimation", "Acclimation", "Signifant acclimation only")) + 
  labs(y=expression('Change in night '~italic('R'[E])~' by 2041-2060 (%)'), x='Scenarios for future '~italic('R'[E])~' projection', tag='f', title='Arid & hot-summer Mediterranean') +
  annotate("text", x = 2, y = 35, label = expression(italic('n')~' = 11, '~italic('n')['significant acclimation']~' = 0'), size = 4.5) + 
  ylim(-10, 37) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 10, hjust = 0.8)) +
  theme(legend.position = "none") +
  theme(plot.title = element_text(hjust = 0.5))
p3
#
p4 <- data.plot %>% filter(Climate_class=="semi_arid_warm_med") %>% ggplot(aes(x=case, y=ratio*100-100)) +
  geom_boxplot(aes(fill=factor(case)), alpha=0.8, outlier.shape = NA, width = 0.6) +
#  geom_jitter() +
  geom_signif(y_position = c(20, 25), xmin = c(1, 1), xmax = c(2, 3),
              annotation = c("**", "**"), tip_length = 0.02) +
  geom_hline(yintercept = 0, color = "black", linetype = "dashed", size = 0.2) +  
  scale_x_discrete(labels = c("No acclimation", "Acclimation", "Signifant acclimation only")) + 
  labs(y=expression('Change in night '~italic('R'[E])~' by 2041-2060 (%)'), x='Scenarios for future '~italic('R'[E])~' projection', tag='d', title='Semi-arid & warm-summer Mediterranean') +
  annotate("text", x = 2, y = 35, label = expression(italic('n')~' = 10, '~italic('n')['significant acclimation']~' = 5'), size = 4.5) + 
  ylim(-10, 37) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 10, hjust = 0.8)) +
  theme(legend.position = "none") +
  theme(plot.title = element_text(hjust = 0.5))
p4
#
p5 <- data.plot %>% filter(Climate_class=="humid") %>% ggplot(aes(x=case, y=ratio*100-100)) +
  geom_boxplot(aes(fill=factor(case)), alpha=0.8, outlier.shape = NA, width = 0.6) +
#  geom_jitter() +
  geom_signif(y_position = c(27, 31), xmin = c(1, 1), xmax = c(2, 3),
              annotation = c("***", "***"), tip_length = 0.02) +
  geom_hline(yintercept = 0, color = "black", linetype = "dashed", size = 0.2) +  
  scale_x_discrete(labels = c("No acclimation", "Acclimation", "Signifant acclimation only")) + 
  labs(y=expression('Change in night '~italic('R'[E])~' by 2041-2060 (%)'), x='Scenarios for future '~italic('R'[E])~' projection', tag='e', title='Humid tropical, subtropical & continental') +
  annotate("text", x = 2, y = 37, label = expression(italic('n')~' = 69, '~italic('n')['significant acclimation']~' = 24'), size = 4.5) + 
  ylim(-10, 37) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 10, hjust = 0.8)) +
  theme(legend.position = "none") +
  theme(plot.title = element_text(hjust = 0.5))
p5
#
p6 <- data.plot %>% filter(Climate_class=="ET") %>% ggplot(aes(x=case, y=ratio*100-100)) +
  geom_boxplot(aes(fill=factor(case)), alpha=0.8, outlier.shape = NA, width = 0.6) +
#  geom_jitter() +
  geom_signif(y_position = c(27, 31), xmin = c(1, 1), xmax = c(2, 3),
              annotation = c("*", "NS."), tip_length = 0.02) +
  geom_hline(yintercept = 0, color = "black", linetype = "dashed", size = 0.2) +  
  scale_x_discrete(labels = c("No acclimation", "Acclimation", "Signifant acclimation only")) + 
  labs(y=expression('Change in night '~italic('R'[E])~' by 2041-2060 (%)'), x='Scenarios for future '~italic('R'[E])~' projection', tag='c', title='Tundra') +
  annotate("text", x = 2, y = 37, label = expression(italic('n')~' = 3, '~italic('n')['significant acclimation']~' = 2'), size = 4.5) + 
  ylim(-10, 37) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 10, hjust = 0.8)) +
  theme(legend.position = "none") +
  theme(plot.title = element_text(hjust = 0.5))
p6

plot_grid(p1, p2, p6, p4, p5, p3, ncol=2, nrow=3, align='hv')
ggsave('Fig4_extent_respiration_mitigation_3cases.png')
#
```


```{r new figure for respiration mitigation by climate classes-four cases-not used, fig.width=8, fig.height=11}
rm(list=ls())
options(na.action = na.omit)
data.future   <- read.csv('acclimation_data_future_ssp245.csv')
data.future$TAmin_c_gs  <- data.future$TSmin_c_gs / data.future$TS_TA
# group the acclimation's effect by climate class
#
data  <- data.future[, c("site_ID", "IGBP", "NEE_night_mod_p", "NEE_night_mod_f", "NEE_night_mod_fa", "NEE_night_mod_fa05", "NEE_night_mod_fa95", "TAmin_c_gs", "TSmin_c_gs")]
#
# connect to thermal acclimation strength
tas  <- read.csv('acclimation_strength.csv')
data <- data %>% left_join(tas, by='site_ID')
# add one more column
data$NEE_night_mod_fa50 <- data$NEE_night_mod_fa
# add one column indicating significance
data$sig <- data$r3_p < 0.1 | data$r3avg_p < 0.1
#
data$Climate_class <- data.future$Climate_class
#
# do climate reclassification
data$Climate_class[data.future$Climate_class %in% c("Bwk", "Csa")] <- 'arid_hot_med'
data$Climate_class[data.future$Climate_class %in% c("Bsk", "Bsh", "Csb")] <- 'semi_arid_warm_med'
#
data$Climate_class[data.future$Climate_class %in% c("Am", "Cfa", "Cfb", "Dfa", "Dfb", "Dfc", "Dfd", "Dwc")] <- 'humid'
#
# soil temperature for different climate class
data3 <- data %>% group_by(Climate_class) %>% summarise(ta_c_m=mean(TAmin_c_gs), ta_c_sd=sd(TAmin_c_gs),
                                                        ts_c_m=mean(TSmin_c_gs), ts_c_sd=sd(TSmin_c_gs))
#
# plot figures; how to add an error bar on the bar?
data_plot  <- data3 %>% dplyr::select(c("Climate_class", "ta_c_m", "ts_c_m"))   %>% rename("ta_c"="ta_c_m",  "ts_c"="ts_c_m")  %>% gather(key='Scenario', value='Temp_mean', -Climate_class)
data_plot1 <- data3 %>% dplyr::select(c("Climate_class", "ta_c_sd", "ts_c_sd")) %>% rename("ta_c"="ta_c_sd", "ts_c"="ts_c_sd") %>% gather(key='Scenario', value='Temp_sd',   -Climate_class)
# set NA standard deviation to 0
data_plot1[is.na(data_plot1)] <- 0.0
# merge the two data frame
data_plot  <- data_plot %>% left_join(data_plot1, by= c("Climate_class", "Scenario"))
#
data_plot$Climate_class <- factor(data_plot$Climate_class, levels=c('arid_hot_med', 'semi_arid_warm_med', 'humid', 'ET'))
#
dodge <- position_dodge(width = 0.75)
p1 <- ggplot(data=data_plot, aes(x=Climate_class, y=Temp_mean, fill=Scenario)) +
  geom_bar(position = "dodge", stat="identity", width=0.75) +  # color = "black"
  geom_errorbar(aes(ymin=Temp_mean-Temp_sd, ymax=Temp_mean+Temp_sd), width = 0.25, position = dodge) +
  scale_x_discrete(labels = c("Arid & hot-summer Mediterranean", "Semi-arid & warm-summer Mediterranean", "Tropical and temperate humid", "Tundra")) + 
  scale_fill_manual(values = c("#D86F6F", "darkgrey"), labels = c("Air temperature", "Soil temperature")) +         #  "#C6E2FF", "grey"
  labs(y='Night temperature rise by 2041-2060 (°C)', x='Aggregated climate class', fill='', tag='a', title='All climates') +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 10, hjust = 0.6, vjust=0.7)) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(legend.position = c(0.25, 0.9),
        legend.text.align = 0,  # Align legend items to the left
        legend.title.align = 0)
p1
#
# Effects on mitigating thermal acclimation
# Do this for all the sites first
# add one more column
data$NEE_night_mod_fa50 <- data$NEE_night_mod_fa
#
###do a correction to future respiration, assuming no overcompensation
threshold <- pmin(data$NEE_night_mod_p, data$NEE_night_mod_f)
data$NEE_night_mod_fa[data$NEE_night_mod_fa < threshold]     <- threshold[data$NEE_night_mod_fa < threshold]
data$NEE_night_mod_fa50[data$NEE_night_mod_fa50 < threshold] <- threshold[data$NEE_night_mod_fa50 < threshold] 
data$NEE_night_mod_fa05[data$NEE_night_mod_fa05 < threshold] <- threshold[data$NEE_night_mod_fa05 < threshold]      # lower limit: stronger acclimation
data$NEE_night_mod_fa95[data$NEE_night_mod_fa95 < threshold] <- threshold[data$NEE_night_mod_fa95 < threshold]      # upper limit: weaker acclimation

# find the sites with significant thermal acclimation
data$NEE_night_mod_fa50[!data$sig] <- data$NEE_night_mod_f[!data$sig]
data$NEE_night_mod_fa05[!data$sig] <- data$NEE_night_mod_f[!data$sig]
data$NEE_night_mod_fa95[!data$sig] <- data$NEE_night_mod_f[!data$sig]

# compensation of significant sites; overcompensation is so common
damp_ratio <- (data$NEE_night_mod_f - data$NEE_night_mod_fa) / (data$NEE_night_mod_f - data$NEE_night_mod_p)
damp_ratio[damp_ratio > 1.0] <- 1
hist(damp_ratio[data$sig])
mean(damp_ratio[data$sig])     # 90 % warming-increased respiration increase

#
damp_ratio95 <- (data$NEE_night_mod_f - data$NEE_night_mod_fa95) / (data$NEE_night_mod_f - data$NEE_night_mod_p)
damp_ratio95[damp_ratio95 > 1.0] <- 1
hist(damp_ratio95[data$sig])
mean(damp_ratio95[data$sig])   # consider the uncertainty: 51 % warming-increased respiration increase

#
# get fractions
data$f_ratio    <- data$NEE_night_mod_f / data$NEE_night_mod_p
data$fa_ratio   <- data$NEE_night_mod_fa / data$NEE_night_mod_p
data$fa50_ratio <- data$NEE_night_mod_fa50 / data$NEE_night_mod_p
data$fa05_ratio <- data$NEE_night_mod_fa05 / data$NEE_night_mod_p
data$fa95_ratio <- data$NEE_night_mod_fa95 / data$NEE_night_mod_p

# mean and sd
# mean(data$f_ratio)       # no thermal acclimation: 1.103819
# mean(data$fa_ratio)      # Optimistic case: 1.05584; 48 %; 
# mean(data$fa50_ratio)    # Realistic case: 1.078439; 25 %
# mean(data$fa95_ratio)    # Pessimistic case: 1.091798: 12 %
# #
# sd(data$f_ratio)       # no thermal acclimation
# sd(data$fa_ratio)      # Optimistic case
# sd(data$fa50_ratio)    # Realistic case
# sd(data$fa95_ratio)    # Pessimistic case

# box plot
data.plot <- data[,c("Climate_class", "f_ratio", "fa_ratio", "fa50_ratio", "fa95_ratio")]
data.plot <- gather(data.plot, key='case', value='ratio', -Climate_class)
p2 <- ggplot(data=data.plot, aes(x=case, y=ratio*100-100)) +
  geom_boxplot(aes(fill=factor(case)), alpha=0.8, outlier.shape = NA) +
#  geom_jitter() +
  geom_hline(yintercept = 0, color = "black", linetype = "dashed", size = 0.2) +  
  scale_x_discrete(labels = c("No acclimation", "Acclimation", "Signifant acclimation only", "Lower limit of acclimation")) + 
  labs(y=expression('Change in night R'[E]~' by 2041-2060 (%)'), x='Scenarios for future R'[E]~' projection', tag='b', title='All climates') +
  ylim(-10, 30) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 10, hjust = 0.8)) +
  theme(legend.position = "none") +
  theme(plot.title = element_text(hjust = 0.5))
p2

######For sites in different climate classes
p3 <- data.plot %>% filter(Climate_class=="arid_hot_med") %>% ggplot(aes(x=case, y=ratio*100-100)) +
  geom_boxplot(aes(fill=factor(case)), alpha=0.8, outlier.shape = NA) +
#  geom_jitter() +
  geom_hline(yintercept = 0, color = "black", linetype = "dashed", size = 0.2) +  
  scale_x_discrete(labels = c("No acclimation", "Acclimation", "Signifant acclimation only", "Lower limit of acclimation")) + 
  labs(y=expression('Change in night R'[E]~' by 2041-2060 (%)'), x='Scenarios for future R'[E]~' projection', tag='c', title='Arid & hot-summer Mediterranean') +
  annotate("text", x = 2.5, y = 28, label = expression(italic('n')~' = 11, '~italic('n')['significant acclimation']~' = 0'), size = 4.5) + 
  ylim(-10, 30) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 10, hjust = 0.8)) +
  theme(legend.position = "none") +
  theme(plot.title = element_text(hjust = 0.5))
p3
#
p4 <- data.plot %>% filter(Climate_class=="semi_arid_warm_med") %>% ggplot(aes(x=case, y=ratio*100-100)) +
  geom_boxplot(aes(fill=factor(case)), alpha=0.8, outlier.shape = NA) +
#  geom_jitter() +
  geom_hline(yintercept = 0, color = "black", linetype = "dashed", size = 0.2) +  
  scale_x_discrete(labels = c("No acclimation", "Acclimation", "Signifant acclimation only", "Lower limit of acclimation")) + 
  labs(y=expression('Change in night R'[E]~' by 2041-2060 (%)'), x='Scenarios for future R'[E]~' projection', tag='d', title='Semi-arid & warm-summer Mediterranean') +
  annotate("text", x = 2.5, y = 28, label = expression(italic('n')~' = 10, '~italic('n')['significant acclimation']~' = 5'), size = 4.5) + 
  ylim(-10, 30) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 10, hjust = 0.8)) +
  theme(legend.position = "none") +
  theme(plot.title = element_text(hjust = 0.5))
p4
#
p5 <- data.plot %>% filter(Climate_class=="humid") %>% ggplot(aes(x=case, y=ratio*100-100)) +
  geom_boxplot(aes(fill=factor(case)), alpha=0.8, outlier.shape = NA) +
#  geom_jitter() +
  geom_hline(yintercept = 0, color = "black", linetype = "dashed", size = 0.2) +  
  scale_x_discrete(labels = c("No acclimation", "Acclimation", "Signifant acclimation only", "Lower limit of acclimation")) + 
  labs(y=expression('Change in night R'[E]~' by 2041-2060 (%)'), x='Scenarios for future R'[E]~' projection', tag='e', title='Tropical and temperate humid') +
  annotate("text", x = 2.5, y = 30, label = expression(italic('n')~' = 69, '~italic('n')['significant acclimation']~' = 24'), size = 4.5) + 
  ylim(-10, 30) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 10, hjust = 0.8)) +
  theme(legend.position = "none") +
  theme(plot.title = element_text(hjust = 0.5))
p5
#
p6 <- data.plot %>% filter(Climate_class=="ET") %>% ggplot(aes(x=case, y=ratio*100-100)) +
  geom_boxplot(aes(fill=factor(case)), alpha=0.8, outlier.shape = NA) +
#  geom_jitter() +
  geom_hline(yintercept = 0, color = "black", linetype = "dashed", size = 0.2) +  
  scale_x_discrete(labels = c("No acclimation", "Acclimation", "Signifant acclimation only", "Lower limit of acclimation")) + 
  labs(y=expression('Change in night R'[E]~' by 2041-2060 (%)'), x='Scenarios for future R'[E]~' projection', tag='f', title='Tundra') +
  annotate("text", x = 2.5, y = 30, label = expression(italic('n')~' = 3, '~italic('n')['significant acclimation']~' = 2'), size = 4.5) + 
  ylim(-10, 30) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 10, hjust = 0.8)) +
  theme(legend.position = "none") +
  theme(plot.title = element_text(hjust = 0.5))
p6

plot_grid(p1, p2, p3, p4, p5, p6, ncol=2, nrow=3, align='hv')
ggsave('Fig4_extent_respiration_mitigation.png')

```

```{r the dangers of extrapolation}
rm(list=ls())
options(na.action = na.omit)
data.future   <- read.csv('acclimation_data_future_ssp245.csv')
sum(data.future$dTS_gs >= data.future$TSmin_c_gs)
#
p1 <- ggplot(data=data.future, aes(x=dTS_gs, y=TSmin_c_gs)) +
  geom_point(size=3) +
  geom_abline(intercept = 0, slope=1, color="black", linetype = "dashed", size = 0.5) +
  annotate("text", x = 1.5, y = 2.6, label = "1:1 line", size = 6, color = "blue", fontface = "bold") +
  labs(x='Interannual differences in mean growing-season soil temperature (°C)' , y='Projected soil temperature changes by 2041-2060 (°C)') + #
  # scale_x_continuous(expand = c(0, 0), lim=c(-0.35, 0.1)) +
  # scale_y_continuous(expand = c(0, 0), lim=c(-0.35, 0.1)) +
  theme_bw() 
p1

ggsave('danger_exterpolation.png', dpi=600)

```


```{r the last figure how acclimation reduces future respiration to SI, fig.width=8, fig.height=8}
# the calculation is in future_respiration.rmd file
# I only plot the figure here.
rm(list=ls())
options(na.action = na.omit)
data.future   <- read.csv('acclimation_data_future_ssp245.csv')
data.future$TAmin_c_gs  <- data.future$TSmin_c_gs / data.future$TS_TA
# group the acclimation's effect by climate class
#
data  <- data.future[, c("site_ID", "IGBP", "NEE_night_mod_p", "NEE_night_mod_f", "NEE_night_mod_fa", "NEE_night_mod_fa05", "NEE_night_mod_fa95", "TAmin_c_gs", "TSmin_c_gs")]
#
#####connect with acclimation strength
tas  <- read.csv('acclimation_data_final.csv')
data <- data %>% left_join(tas, by='site_ID')
data$significant <- data$r3avg_p < 0.1
#######
###to do a correction to future respiration
threshold <- pmin(data$NEE_night_mod_p, data$NEE_night_mod_f)
data$NEE_night_mod_fa[data$NEE_night_mod_fa < threshold] <- data$NEE_night_mod_p[data$NEE_night_mod_fa < threshold]
###
data$NEE_night_mod_fa50 <- data$NEE_night_mod_fa
data$NEE_night_mod_fa50[!data$significant] <- data$NEE_night_mod_f[!data$significant]
####----------------------------------------------------------------------------------------------------------------
# group by climate class
data3 <- data %>% group_by(Climate_class) %>% summarise(mod_p_m=mean(NEE_night_mod_p), mod_p_sd=sd(NEE_night_mod_p), 
                                      mod_f_m=mean(NEE_night_mod_f),       mod_f_sd=sd(NEE_night_mod_f),
                                      mod_fa_m=mean(NEE_night_mod_fa),     mod_fa_sd=sd(NEE_night_mod_fa),
                                      mod_fa50_m=mean(NEE_night_mod_fa50), mod_fa50_sd=sd(NEE_night_mod_fa50),
                                      ta_c_m=mean(TAmin_c_gs), ta_c_sd=sd(TAmin_c_gs),
                                      ts_c_m=mean(TSmin_c_gs), ts_c_sd=sd(TSmin_c_gs))
#
data3$reduction   <- (data3$mod_f_m-data3$mod_fa_m)/(data3$mod_f_m-data3$mod_p_m)
data3$increase_f  <- data3$mod_f_m / data3$mod_p_m
data3$increase_fa <- data3$mod_fa_m / data3$mod_p_m
#
# plot figures; how to add an error bar on the bar?
data_plot  <- data3 %>% dplyr::select(c("Climate_class", "ta_c_m", "ts_c_m"))   %>% rename("ta_c"="ta_c_m",  "ts_c"="ts_c_m")  %>% gather(key='Scenario', value='Temp_mean', -Climate_class)
data_plot1 <- data3 %>% dplyr::select(c("Climate_class", "ta_c_sd", "ts_c_sd")) %>% rename("ta_c"="ta_c_sd", "ts_c"="ts_c_sd") %>% gather(key='Scenario', value='Temp_sd',   -Climate_class)
# set NA standard deviatioin to 0
data_plot1[is.na(data_plot1)] <- 0.0
# merge the two data frame
data_plot  <- data_plot %>% left_join(data_plot1, by= c("Climate_class", "Scenario"))
#
#
dodge <- position_dodge(width = 0.6)
p1 <- ggplot(data=data_plot, aes(x=Climate_class, y=Temp_mean, fill=Scenario)) +
  geom_bar(position = "dodge", stat="identity", width=0.6, color = "black", size=0.3) +  # 
  geom_errorbar(aes(ymin=Temp_mean-Temp_sd, ymax=Temp_mean+Temp_sd), width = 0.25, position = dodge, size=0.3) +
  geom_vline(xintercept = 1.5, color = "black", linetype = "dotted", size = 0.2) +  
  geom_vline(xintercept = 4.5, color = "black", linetype = "dotted", size = 0.2) +
  geom_vline(xintercept = 6.5, color = "black", linetype = "dotted", size = 0.2) +
  geom_vline(xintercept = 8.5, color = "black", linetype = "dotted", size = 0.2) +
  geom_vline(xintercept = 13.5, color = "black", linetype = "dotted", size = 0.2) +
  scale_fill_manual(values = c("#ECECEC", "darkgrey"), labels = c("Air temperature", "Topsoil temperature")) +         # "#9473b3", "#845d52", "#C6E2FF", "grey" 
  labs(y='Growing-season night temperature rise (°C)', x='The Köppen climate class', fill='', tag='a') +
  theme_classic() +
  theme(legend.position = c(0.85, 0.94),
        legend.text.align = 0,  # Align legend items to the left
        legend.title.align = 0)

# EBF almost has no acclimation
data_plot3 <- data3 %>% dplyr::select(c("Climate_class", "mod_p_m", "mod_f_m", "mod_fa_m", "mod_fa50_m")) %>% rename("mod_p"="mod_p_m", "mod_f"="mod_f_m", "mod_fa"="mod_fa_m", "mod_fa50"="mod_fa50_m") %>% gather(key='Scenario', value='ER_mean', -Climate_class)
data_plot2 <- data3 %>% dplyr::select(c("Climate_class", "mod_p_sd", "mod_f_sd", "mod_fa_sd", "mod_fa50_sd")) %>% rename("mod_p"="mod_p_sd", "mod_f"="mod_f_sd", "mod_fa"="mod_fa_sd", "mod_fa50"="mod_fa50_sd") %>% gather(key='Scenario', value='ER_sd', -Climate_class)
#
data_plot2[is.na(data_plot2)] <- 0.0
data_plot3 <- data_plot3 %>% left_join(data_plot2, by= c("Climate_class", "Scenario"))
#
#
data_plot3$Scenario <- factor(data_plot3$Scenario, levels=c('mod_p', 'mod_f', 'mod_fa50', 'mod_fa'))
dodge <- position_dodge(width = 0.75)
p2 <- ggplot(data=data_plot3, aes(x=Climate_class, y=ER_mean*12, fill=Scenario)) +
  geom_bar(position="dodge", stat="identity", width=0.75, size=0.5) +
  geom_errorbar(aes(ymin=(ER_mean-ER_sd)*12, ymax=(ER_mean+ER_sd)*12), width = 0.3, position = dodge, size=0.3) +
  geom_vline(xintercept = 1.5, color = "black", linetype = "dotted", size = 0.2) +  
  geom_vline(xintercept = 4.5, color = "black", linetype = "dotted", size = 0.2) +
  geom_vline(xintercept = 6.5, color = "black", linetype = "dotted", size = 0.2) +
  geom_vline(xintercept = 8.5, color = "black", linetype = "dotted", size = 0.2) +
  geom_vline(xintercept = 13.5, color = "black", linetype = "dotted", size = 0.2) +
  scale_fill_manual(values = c("#619cff", "#fa938d", "#51ccd1", "#99bf46"), labels = c(expression('Current R'[E]), expression('Future R'[E]~'without acclimation'),expression('Future R'[E]~'with significant acclimation only'), expression('Future R'[E]~'with acclimation'))) +
  labs(y=expression('Growing-season night R'[E]~' (µg CO'[2]~ ' m'^{-2}~ ' s'^{-1}~')'), x='The Köppen climate class', fill='', tag='b') +
  theme_classic() +
  theme(legend.position = c(0.75, 0.95),
        legend.text = element_text(size = 8),
        legend.key.size = unit(0.4, "cm"),
        legend.text.align = 0,  # Align legend items to the left
        legend.title.align = 0)

# merge the two figures
plot_grid(p1, p2, nrow=2, ncol=1)

ggsave('Effects_of_future_thermal_acclimation_SI.png', dpi=600)
# 
# calculate climate-specific values
tas.stat <- tas %>% group_by(Climate_class) %>% summarise(tas_m=mean(r3avg), tas_sd=sd(r3avg)) 
tas.stat
#
data$f_ratio    <- data$NEE_night_mod_f / data$NEE_night_mod_p
data$fa_ratio   <- data$NEE_night_mod_fa / data$NEE_night_mod_p
data$fa50_ratio <- data$NEE_night_mod_fa50 / data$NEE_night_mod_p
#
data.stat1 <- data %>% group_by(Climate_class) %>% summarise(f_ratio_m = mean(f_ratio), f_ratio_sd = sd(f_ratio), 
                                                             fa_ratio_m = mean(fa_ratio), fa_ratio_sd = sd(fa_ratio),
                                                             fa50_ratio_m = mean(fa50_ratio), fa50_ratio_sd = sd(fa50_ratio), n=n()) 
data.stat1

```

```{r relationship between significance level and data length, fig.width=8, fig.height=4}
#
acclimation <- read.csv('acclimation_data_final.csv')
#
p1 <- ggplot(data=acclimation, aes(x=nyear, fill=significant, color=significant)) +
  geom_histogram(position="identity", alpha=0.5) +
  labs(x='Duration of data (years)', y="Numer of sites", color='Significant acclimation', fill='Significant acclimation', tag='a') +
  theme_classic() +
  theme(legend.position = c(0.75, 0.8))  
#
#
sig.frac <- data.frame(duration=seq(8, 20, 4), fraction=0)  # ~ 30 % of our sites have no longer than 10 years of data. 
#
for (i in 1:nrow(sig.frac)) {
  sig.frac$fraction[i] <- sum(acclimation$nyear > sig.frac$duration[i] & acclimation$significant) / sum(acclimation$nyear > sig.frac$duration[i])
}
#
plot(data=sig.frac, fraction~duration)   # I should put the two figures together, significance fraction can be 60 % if the data duration ≥20 years 
p2 <- ggplot(data=sig.frac, aes(x=duration, y=fraction*100)) +
  geom_bar(stat = "identity", fill='grey', width=2) +
  scale_x_continuous(breaks = c(8, 12, 16, 20), labels = c("≥8", "≥12", "≥16", "≥20")) +
  labs(x='Duration of data (years)', y="Sites with significant compensating acclimation (%)", tag='b') +
  theme_classic()  
#
plot_grid(p1, p2, nrow=1, ncol=2)
ggsave('SI_data_duration_significance.png')  
  

# bin.all  <- hist(acclimation$nyear)
# #
# bin.sig  <- hist(acclimation$nyear[acclimation$significant])
# #
# bin.nonsig  <- hist(acclimation$nyear[!acclimation$significant])
# #
# bin.frac <- bin.all
# #
# bin.frac$counts <- bin.sig$counts / bin.all$counts
# #
# plot(bin.frac)

```








```{r I need to have another figure to show the uncertainty, this is a test figure only}
rm(list=ls())
options(na.action = na.omit)
####
# scenarios   <- c("ssp126", "ssp245", "ssp370", "ssp585")
# data_plot4  <- data.frame(scenarios=scenarios, )
#### Differences among different scenarios can be ignored. 

data.future   <- read.csv('acclimation_data_future_ssp245.csv')
data.future$TAmin_c_gs  <- data.future$TSmin_c_gs / data.future$TS_TA
# group the acclimation's effect by climate class
#
data  <- data.future[, c("site_ID", "IGBP", "NEE_night_mod_p", "NEE_night_mod_f", "NEE_night_mod_fa", "NEE_night_mod_fa05", "NEE_night_mod_fa95", "TAmin_c_gs", "TSmin_c_gs")]
#
# connect to thermal acclimation strength
tas  <- read.csv('acclimation_strength.csv')
data <- data %>% left_join(tas, by='site_ID')
# add one more column
data$NEE_night_mod_fa50 <- data$NEE_night_mod_fa

#
###do a correction to future respiration, assuming no overcompensation
threshold <- pmin(data$NEE_night_mod_p, data$NEE_night_mod_f)
data$NEE_night_mod_fa[data$NEE_night_mod_fa < threshold]     <- threshold[data$NEE_night_mod_fa < threshold]
data$NEE_night_mod_fa50[data$NEE_night_mod_fa50 < threshold] <- threshold[data$NEE_night_mod_fa50 < threshold] 
data$NEE_night_mod_fa05[data$NEE_night_mod_fa05 < threshold] <- threshold[data$NEE_night_mod_fa05 < threshold]      # lower limit: stronger acclimation
data$NEE_night_mod_fa95[data$NEE_night_mod_fa95 < threshold] <- threshold[data$NEE_night_mod_fa95 < threshold]      # upper limit: weaker acclimation

# find the sites with significant thermal acclimation
data$NEE_night_mod_fa50[data$r3avg_p > 0.1] <- data$NEE_night_mod_f[data$r3avg_p > 0.1]
data$NEE_night_mod_fa05[data$r3avg_p > 0.1] <- data$NEE_night_mod_f[data$r3avg_p > 0.1]
data$NEE_night_mod_fa95[data$r3avg_p > 0.1] <- data$NEE_night_mod_f[data$r3avg_p > 0.1]

# compensation of significant sites; overcompensation is so common
damp_ratio <- (data$NEE_night_mod_f - data$NEE_night_mod_fa) / (data$NEE_night_mod_f - data$NEE_night_mod_p)
damp_ratio[damp_ratio > 1.0] <- 1
hist(damp_ratio[data$r3avg_p <= 0.1])
mean(damp_ratio[data$r3avg_p <= 0.1])     # 90 % warming-increased respiration increase

#
damp_ratio95 <- (data$NEE_night_mod_f - data$NEE_night_mod_fa95) / (data$NEE_night_mod_f - data$NEE_night_mod_p)
damp_ratio95[damp_ratio95 > 1.0] <- 1
hist(damp_ratio95[data$r3avg_p <= 0.1])
mean(damp_ratio95[data$r3avg_p <= 0.1])   # consider the uncertainty: 51 % warming-increased respiration increase
#

#
# get fractions
data$f_ratio    <- data$NEE_night_mod_f / data$NEE_night_mod_p
data$fa_ratio   <- data$NEE_night_mod_fa / data$NEE_night_mod_p
data$fa50_ratio <- data$NEE_night_mod_fa50 / data$NEE_night_mod_p
data$fa05_ratio <- data$NEE_night_mod_fa05 / data$NEE_night_mod_p
data$fa95_ratio <- data$NEE_night_mod_fa95 / data$NEE_night_mod_p

# mean and sd
mean(data$f_ratio)       # no thermal acclimation: 1.103819
mean(data$fa_ratio)      # Optimistic case: 1.05584; 48 %; 
mean(data$fa50_ratio)    # Realistic case: 1.078439; 25 %
mean(data$fa95_ratio)    # Pessimistic case: 1.091798: 12 %
#
sd(data$f_ratio)       # no thermal acclimation
sd(data$fa_ratio)      # Optimistic case
sd(data$fa50_ratio)    # Realistic case
sd(data$fa95_ratio)    # Pessimistic case

# box plot
data.plot <- data[,c("f_ratio", "fa_ratio", "fa50_ratio", "fa95_ratio")]
data.plot <- gather(data.plot, key='case', value='ratio')
ggplot(data=data.plot, aes(x=case, y=ratio*100-100)) +
  geom_boxplot(aes(fill=factor(case)), alpha=0.8, outlier.shape = NA) +
#  geom_jitter() +
  geom_hline(yintercept = 0, color = "black", linetype = "dashed", size = 0.2) +  
  scale_x_discrete(labels = c("No acclimation for all sites", "Acclimation for all sites", "Acclimation for sites with significant TAS", "Lower limit of acclimation")) + 
  labs(y=expression('Change in night R'[E]~' by 2041-2060 (%)'), x='Different scenarios for future R'[E]~' projection') +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 10, hjust = 1)) +
  theme(legend.position = "none")
ggsave('future_respriation_change.png', dpi=600)

```


