---
title: "future_respiration"
output: pdf_document
date: "2024-06-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r estimate current and future respiration}
library(tidyverse)
library(gslnls)
library(caret)
library(performance)
library(zoo)
rm(list=ls())
options(na.action = "na.omit")
# read data used for this module 
#
root.dir <- '/Users/jw2946/Documents/stability_project/code_acclimation/driver_analysis/'
acclimation <- read.csv(file.path(root.dir, "basic_site_info.csv"))
#
acclimation.strength <- read.csv(file.path(root.dir, 'acclimation_strength.csv'))
acclimation     <- acclimation %>% left_join(acclimation.strength, by='site_ID')
#
#
Tmin_month <- read.csv(file.path(root.dir, 'Tmin_month_ssp245_wc.csv'))
acclimation     <- acclimation %>% left_join(Tmin_month, by='site_ID')
#
# add 6 column about respiration
acclimation$TS_TA   <- 0            # conversion between TS and TA
acclimation$TSmin_c <- 0            # monthly min soil temperature change
acclimation$TSmin_c_gs <- 0         # gs: growing season
acclimation$NEE_night_mod_p <- 0
acclimation$NEE_night_mod_f <- 0
acclimation$NEE_night_mod_fa <- 0
acclimation$NEE_night_mod_fa95 <- 0
acclimation$NEE_night_mod_fa05 <- 0
#
data.dir    <- '/Users/jw2946/Documents/stability_project/RespiarationData/ALL10122024/'
files  <- list.files(data.dir, pattern = '_ac.RDS$', full.names = TRUE)
# workflow
# air and soil temperature patterns
for (i in 1:length(files)) {
#  i = 35
  name_site <- substring(files[i], nchar(files[i])-12, nchar(files[i])-7)
  print(paste0(i, name_site))
  #
  iacclimation <- which(acclimation$site_ID==name_site)
  #
  ac <- readRDS(files[i])
  #
  # use only the years with qualified data
  outcome <- readRDS(paste0(data.dir, name_site, '_outcome.RDS'))
  good_years <- as.integer(colnames(outcome$result)[!is.na(outcome$result[1,])])
  good_years <- good_years[!is.na(good_years)]
  # recalculate TS_TA relationship using TA threshold
  if (name_site!='GF-Guy') {
    tmp <- ac %>% filter(TA > 0)   # only use the data with TA > 0C; use another range to calculate the coefficient
    outcome$TS_TA <- summary(lm(data=tmp, TS~TA))$coefficients[2,1]
  }
  #
  night_pattern <- ac %>% filter(YEAR %in% good_years & !daytime) %>% group_by(DOY, HOUR, MINUTE, MONTH) %>% summarise(TAp=mean(TA, na.rm=T), TSp=mean(TS, na.rm=T), SWC=mean(SWC, na.rm=T), NEEo=mean(NEE, na.rm=T))
  # remove duplicate rows
  night_pattern  <- night_pattern[!duplicated(night_pattern[,c('DOY', 'HOUR', 'MINUTE')]), ]
  # deal with occasional TA missing cases
  if (sum(is.na(night_pattern$TAp)) > 0) {
    night_pattern$TAp <- na.approx(night_pattern$TAp)
  }
  # deal with occasional TS missing cases
  if (sum(is.na(night_pattern$TSp)) > 0) {
    mod_lm <- lm(data=night_pattern, TSp ~ TAp)
    TSp_pred <- predict(mod_lm, night_pattern)
    night_pattern$TSp[is.na(night_pattern$TSp)] <- TSp_pred[is.na(night_pattern$TSp)]
  }
  #
  temp_change   <- data.frame(MONTH=1:12, TAmnc=as.numeric(acclimation[iacclimation, which(colnames(acclimation) %in% (paste0('Tmin', 1:12)))]))
  #
  night_pattern <- night_pattern %>% left_join(temp_change, by="MONTH")
  #
  night_pattern$TAf <- night_pattern$TAp + night_pattern$TAmnc
  night_pattern$TSf <- night_pattern$TSp + night_pattern$TAmnc * outcome$TS_TA
  #
  data <- readRDS(paste0(data.dir, name_site, '_nightNEE.RDS'))
  if (acclimation$SWC_use[acclimation$site_ID==name_site]=='YES') {
    # fit the temperature respiration model
    frmu   <- NEE ~ C_pool * exp(alpha * TS + beta*TS^2)  * SWC / (Hs + SWC)     # in this formula: C_pool, alpha, beta, and Hs are unclear parameters. I know Cpool and Hs should be positive;
    if (name_site=='ZA-Kru') {
      stprm  <- c(C_pool=10, alpha=0.1, beta=-0.01, Hs = 100)
    } else if (name_site=='GF-Guy') {
      stprm  <- c(C_pool=1, alpha=0.1, beta=-0.001, Hs = 20)
    } else {
      stprm  <- c(C_pool=1, alpha=0.1, beta=-0.01, Hs = 20) # 
    }
    df_accurate <- data.frame(NEE=data$NEE, TS=data$TS, SWC=data$SWC)
    mod2 <- gsl_nls(fn=frmu, data=df_accurate, start=stprm)
    summary(mod2)
    NEE_pred <- predict(mod2, newdata=df_accurate)
    plot(df_accurate$TS, df_accurate$NEE)
    # check performance
    postResample(pred=NEE_pred, obs=df_accurate$NEE)
    # predict current night respiration
    # firstly, deal with occasional SWC missing cases using linear regression
    if (sum(is.na(night_pattern$SWC)) > 0) {
      night_pattern$time <- night_pattern$DOY + night_pattern$HOUR / 24 + night_pattern$MINUTE / 60 / 24
      # re-order the data
      night_pattern <- night_pattern %>% arrange(time)
      # then linear interpolation
      night_pattern$SWC.appr <- na.approx(night_pattern$SWC, night_pattern$time, na.rm = FALSE)
      # dealing with missing head and end data
      num_min <- min(which(!is.na(night_pattern$SWC.appr)))
      num_max <- max(which(!is.na(night_pattern$SWC.appr)))
      if (num_min > 1) {
        night_pattern$SWC.appr[1:(num_min-1)] <- night_pattern$SWC.appr[num_min]
      }
      if (num_max < nrow(night_pattern)) {
        night_pattern$SWC.appr[(num_max+1):nrow(night_pattern)] <- night_pattern$SWC.appr[num_max]
      }
      night_pattern$SWC <- night_pattern$SWC.appr
      night_pattern$SWC.appr <- NULL
    }
    #
    df_present <- data.frame(TS=night_pattern$TSp, SWC= night_pattern$SWC)
    night_pattern$NEEp <- predict(mod2, newdata=df_present)
    #
    # predict for future respiration
    df_future <- data.frame(TS=night_pattern$TSf, SWC= night_pattern$SWC)
    night_pattern$NEEf <- predict(mod2, newdata=df_future)    
  } else {
    frmu   <- NEE ~ C_pool * exp(alpha * TS + beta*TS^2)
    stprm  <- c(C_pool=1, alpha=0.1, beta=-0.01) # 
    df_accurate <- data.frame(NEE=data$NEE, TS=data$TS)
    mod2 <- gsl_nls(fn=frmu, data=df_accurate, start=stprm)
    summary(mod2)
    NEE_pred <- predict(mod2, newdata=df_accurate)
    plot(df_accurate$TS, df_accurate$NEE)
    # check performance
    postResample(pred=NEE_pred, obs=df_accurate$NEE)
    # predict current night respiration
    #
    df_present <- data.frame(TS=night_pattern$TSp)
    night_pattern$NEEp <- predict(mod2, newdata=df_present)
    #
    # predict for future respiration
    df_future <- data.frame(TS=night_pattern$TSf)
    night_pattern$NEEf <- predict(mod2, newdata=df_future)     
  }
  # get the required values
  acclimation$TS_TA[iacclimation] <- outcome$TS_TA
  acclimation$TSmin_c[iacclimation] <- mean(temp_change$TAmnc) * outcome$TS_TA
  #
  # dt <- abs(ac$MINUTE[2] + ac$HOUR[2] * 60 - ac$MINUTE[1] - ac$HOUR[1] * 60)
  # acclimation$NEE_night_mod_p[iacclimation]  <- sum(night_pattern$NEEp) * dt * 60 / 1000000 * 12        ### g C / m2;
  # acclimation$NEE_night_mod_f[iacclimation]  <- sum(night_pattern$NEEf) * dt * 60 / 1000000 * 12        ### g C / m2;
  #
  # predicting separate the growing season and non-growing season
  # NEE_gs <- sum(night_pattern$NEEf[night_pattern$DOY >= outcome$gStart & night_pattern$DOY <= outcome$gEnd]) * dt * 60 / 1000000 * 12
  # TSmin_c_gs <- mean(night_pattern$TAmnc[night_pattern$DOY >= outcome$gStart & night_pattern$DOY <= outcome$gEnd]) * outcome$TS_TA
  # NEE_ng <- sum(night_pattern$NEEf[night_pattern$DOY < outcome$gStart | night_pattern$DOY > outcome$gEnd]) * dt * 60 / 1000000 * 12
  # acclimation$NEE_night_mod_fa[iacclimation] <- NEE_gs * exp(acclimation$r3avg[iacclimation] * TSmin_c_gs) + NEE_ng
  # print(NEE_gs * exp(acclimation$r3avg[iacclimation] * TSmin_c_gs)/NEE_ng)
  #
  # acclimation$NEE_night_mod_fa[iacclimation] <- acclimation$NEE_night_mod_f[iacclimation] * exp(acclimation$r3avg[iacclimation] * mean(temp_change$TAmnc) * outcome$TS_TA)
  #
  # NEE during growing season only
  acclimation$NEE_night_mod_p[iacclimation]  <- mean(night_pattern$NEEp[night_pattern$DOY >= outcome$gStart & night_pattern$DOY <= outcome$gEnd])
  acclimation$NEE_night_mod_f[iacclimation]  <- mean(night_pattern$NEEf[night_pattern$DOY >= outcome$gStart & night_pattern$DOY <= outcome$gEnd])
  NEE_gs <- mean(night_pattern$NEEf[night_pattern$DOY >= outcome$gStart & night_pattern$DOY <= outcome$gEnd]) 
  acclimation$TSmin_c_gs[iacclimation] <- mean(night_pattern$TAmnc[night_pattern$DOY >= outcome$gStart & night_pattern$DOY <= outcome$gEnd]) * outcome$TS_TA
  acclimation$NEE_night_mod_fa[iacclimation] <- NEE_gs * exp(acclimation$r3avg[iacclimation] * acclimation$TSmin_c_gs[iacclimation])
  #
  acclimation$NEE_night_mod_fa95[iacclimation] <- NEE_gs * exp(acclimation$r3avg95[iacclimation] * acclimation$TSmin_c_gs[iacclimation])
  acclimation$NEE_night_mod_fa05[iacclimation] <- NEE_gs * exp(acclimation$r3avg05[iacclimation] * acclimation$TSmin_c_gs[iacclimation])  
}
# what are the statistical results I want to pull out?
# our predicted present NEE night is fairly close to our observed NEE night; they are not comparable now, because one is growing season, other is annual 
# cor.test(acclimation$NEE_night, acclimation$NEE_night_mod_p)  # correlation: 0.987411
# #
# plot(acclimation$NEE_night, acclimation$NEE_night_mod_p) 
# abline(a=0, b=1)
#
# the sites whose prediction is not very accurate: US-Ha1, US-Var (grassland in dry area), CA-Ca1, IT-Lav, IT-Tor
#
write.csv(acclimation, file='/Users/jw2946/Documents/stability_project/manuscripts/plot/acclimation_data_future.csv', row.names = F)
#
# compare the difference between inter-annual differences of mean growing-season soil temperature and future soil temperature increase for all the sites. 
ggplot(data=acclimation, aes(x=TSmin_c_gs, y=dTS_gs)) +
  geom_point() +
  geom_abline(slope=1, intercept=0, col='blue') +
  labs(x='Future soil temperature rise (°C)', y='Inter-annual differences of growing-season soil temperature (°C)')
# 5 outliers in ssp245
# 12 outliers in ssp585

ggplot(data=acclimation, aes(x=nyear, y=dTS_gs)) +
  geom_point() +
  labs(x='Number of data years', y='Inter-annual differences of growing-season soil temperature (°C)')
cor.test(acclimation$nyear, acclimation$dTS_gs)  # p = 0.01294

#
par(mfrow = c(2, 3))
hist(acclimation$NEE_night_mod_p, breaks=20)
hist(acclimation$NEE_night_mod_f, breaks=20)
hist(acclimation$NEE_night_mod_fa, breaks=20)
hist(acclimation$NEE_night_mod_fa, breaks=20)
hist(acclimation$NEE_night_mod_fa95, breaks=20)
hist(acclimation$NEE_night_mod_fa05, breaks=20)
#
```

```{r statistics of future respiration, fig.width=20, fig.height=10}
data      <- acclimation[, c("site_ID", "IGBP", "NEE_night_mod_p", "NEE_night_mod_f", "NEE_night_mod_fa")]
data$Climate_class <- acclimation$Climate_class
#

# add temperature change as well1
plot.data <- data %>% dplyr::select(-c("Climate_class")) %>% gather(key="scenario", value='NEE_night', -c(site_ID, IGBP)) 
order.data <- plot.data%>% arrange(IGBP)
plot.data$site_ID <- factor(plot.data$site_ID, levels=unique(order.data$site_ID))
#   "IGBP", 
ggplot(data=plot.data, aes(x=site_ID, y=NEE_night, shape=scenario, color=IGBP)) +
  geom_point()
#
data2 <- data %>% group_by(IGBP) %>% summarise(mod_p_m=mean(NEE_night_mod_p),   mod_p_sd=sd(NEE_night_mod_p), 
                                      mod_f_m=mean(NEE_night_mod_f),   mod_f_sd=sd(NEE_night_mod_f),
                                      mod_fa_m=mean(NEE_night_mod_fa), mod_fa_sd=sd(NEE_night_mod_fa))
# why overall respiration is unlikely to increase so much with warming?
# the Buffering effects of plants and soil temperature increase is generally smaller than air temperature except in arid and semi-arid areas.
# other factors limiting respiration such as water
# the last and most important thing is acclimation
# some calculation for data2
data2$reduction   <- (data2$mod_f_m-data2$mod_fa_m)/(data2$mod_f_m-data2$mod_p_m)
data2$increase_f  <- data2$mod_f_m / data2$mod_p_m
data2$increase_fa <- data2$mod_fa_m / data2$mod_p_m

# other calculations
# EBF almost has no acclimation
data_plot2 <- data2 %>% dplyr::select(c("IGBP", "mod_p_m", "mod_f_m", "mod_fa_m")) %>% gather(key='Scenario', value='NEE_night', -IGBP)
#
data_plot2$Scenario <- factor(data_plot2$Scenario, levels=c('mod_p_m', 'mod_f_m', 'mod_fa_m'))
ggplot(data=data_plot2, aes(x=IGBP, y=NEE_night, fill=Scenario)) +
  geom_bar(position="dodge", stat="identity") +
  scale_fill_manual(values = c("#00AFBB", "#FC4E07", "#E7B800"), labels = c('Current ER', 'Future ER no acclimation', 'Future ER with acclimation')) +
  labs(y='Mean annual night NEE (mol CO2 / m2)')
####
####----------------------------------------------------------------------------------------------------------
# group by climate class
data3 <- data %>% group_by(Climate_class) %>% summarise(mod_p_m=mean(NEE_night_mod_p), mod_p_sd=sd(NEE_night_mod_p), 
                                      mod_f_m=mean(NEE_night_mod_f),   mod_f_sd=sd(NEE_night_mod_f),
                                      mod_fa_m=mean(NEE_night_mod_fa), mod_fa_sd=sd(NEE_night_mod_fa))
#
data3$reduction   <- (data3$mod_f_m-data3$mod_fa_m)/(data3$mod_f_m-data3$mod_p_m)
data3$increase_f  <- data3$mod_f_m / data3$mod_p_m
data3$increase_fa <- data3$mod_fa_m / data3$mod_p_m

# other calculations
# EBF almost has no acclimation
data_plot3 <- data3 %>% dplyr::select(c("Climate_class", "mod_p_m", "mod_f_m", "mod_fa_m")) %>% gather(key='Scenario', value='NEE_night', -Climate_class)
#
data_plot3$Scenario <- factor(data_plot3$Scenario, levels=c('mod_p_m', 'mod_f_m', 'mod_fa_m'))
ggplot(data=data_plot3, aes(x=Climate_class, y=NEE_night, fill=Scenario)) +
  geom_bar(position="dodge", stat="identity") +
  scale_fill_manual(values = c("#00AFBB", "#FC4E07", "#E7B800"), labels = c('Current ER', 'Future ER no acclimation', 'Future ER with acclimation')) +
  labs(y='Mean annual night NEE (mol CO2 / m2)')


```

```{r air and soil temperature ratio distribution}
ggplot(data=acclimation, aes(x=Climate.Class.Abbreviation..Koeppen., y=TS_TA)) +
  geom_boxplot()


```

```{r read soil water data}
file <- read.table('/Users/jw2946/Downloads/FR-Pue_SWC_Control_Corrected_2003-2015.csv', sep=';', header=T)
plot(file$SWC_Mean)


```

