---
title: "fluxnet"
output: pdf_document
date: "2024-03-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r read data and check data quality}
library(dplyr)
library(lubridate)
rm(list=ls())
#
name_site <- 'ZA-Kru'
path  <- '/Users/jw2946/Documents/stability_project/FluxNet/unzip/'
if (name_site %in% c('AU-Tum', 'BR-Sa1')) {
  pattern <- paste0('FLX_', name_site, '_FLUXNET2015_FULLSET_HR_')
} else {
  pattern <- paste0('FLX_', name_site, '_FLUXNET2015_FULLSET_HH_')
}
file  <- list.files(path=path, pattern = pattern, full.names = TRUE)
#
a <- read.csv(file)
# add more columns
  dt <- ymd_hm(a$TIMESTAMP_START[2]) - ymd_hm(a$TIMESTAMP_START[1])
  a$TIMESTAMP  <- ymd_hm(a$TIMESTAMP_START) + dt / 2
  a$YEAR  <- year(a$TIMESTAMP)
  a$MONTH <- month(a$TIMESTAMP)
  a$DAY   <- day(a$TIMESTAMP)
  a$DOY   <- yday(a$TIMESTAMP)
  a$HOUR  <- hour(a$TIMESTAMP)
  a$MINUTE <- minute(a$TIMESTAMP)
  # Southern Hemisphere, so we need to change DOY values
  if (name_site %in% c('AU-Tum', 'ZA-Kru')) {
    a$DOY[a$DOY < 183] <- a$DOY[a$DOY < 183] + 366
  }
#
  # check the missed dataset
  SWC <- TRUE
  if (!'SWC_F_MDS_1' %in% colnames(a)) {
    a$SWC_F_MDS_1 <- NA
    SWC <- FALSE
  }
  #
  # The four important variables I need to look for: TS, TA, SWC, NEE
  # the corresponding variable names
  plot(a$TA_ERA)
  plot(a$TS_F_MDS_1, ylim=c(-25,50))   # quality control == -9999 is missing data, 3 = poor, so filtering these data
  plot(a$SWC_F_MDS_1) 
  plot(a$NEE_VUT_REF)  # I should use QC=0, measured data
  
  # can we loose the SWC constrains
  a_measure_night_complete <- a %>% filter(TA_ERA != -9999) %>% filter(TS_F_MDS_1_QC %in% c(0, 1, 2)) %>% filter(NEE_VUT_REF_QC == 0) %>% filter(NIGHT == 1) %>% filter(NEE_VUT_REF > -5 & NEE_VUT_REF < 20) 
  # %>% filter(SWC_F_MDS_1_QC %in% c(0, 1, 2))
  #
  # plot the data of each year
  yStart <- a_measure_night_complete$YEAR[1]
  yEnd   <- a_measure_night_complete$YEAR[nrow(a_measure_night_complete)]
  good_years <- c()
  for (i in yStart:yEnd) {
    data <- a_measure_night_complete %>% filter(YEAR==i)
    if (nrow(data) > 100) {
      plot(data$TS_F_MDS_1, data$NEE_VUT_REF, main=i)
      plot(data$TIMESTAMP, data$NEE_VUT_REF, main=i, xlim=c(as.POSIXct(paste0(i, "-01-01 00:00:00")), as.POSIXct(paste0(i, "-12-31 00:00:00"))))
      good_years <- c(good_years, i)
    } else {
      print(i)
    }
  }
#  good_years
a_measure_night_complete <- a_measure_night_complete %>% filter(!YEAR %in% c(2000, 2006, 2013))
# change column names
a_measure_night_complete$TA <- a_measure_night_complete$TA_ERA
a_measure_night_complete$TS <- a_measure_night_complete$TS_F_MDS_1
a_measure_night_complete$SWC <- a_measure_night_complete$SWC_F_MDS_1
a_measure_night_complete$NEE <- a_measure_night_complete$NEE_VUT_REF
#
# other information I need:
a[a==-9999] <- NA
NEE_yearly  <- a %>% group_by(DOY) %>% summarise(NEE=mean(NEE_VUT_REF, na.rm=T), TS=mean(TS_F_MDS_1, na.rm=T))   # replace the name of NEE;
plot(NEE_yearly$DOY, NEE_yearly$NEE)
plot(NEE_yearly$DOY, NEE_yearly$TS)
#
# I will use the mean of the first three values, and the mean of the last three values
tmp    <- NEE_yearly %>% filter(NEE < max(min(NEE_yearly$NEE, na.rm=T) * 0.2, -0.8))
gStart <- as.integer(mean(tmp$DOY[7])) - 4
gEnd   <- as.integer(mean(tmp$DOY[(nrow(tmp)-6)])) + 4
gStart
gEnd   
#
# temperature range of growing season
tStart = as.integer(quantile(tmp$TS, c(0.025), na.rm=T) * 10) + 1     #
tEnd   = as.integer(quantile(tmp$TS, c(0.975), na.rm=T) * 10) + 1     #
tStart
tEnd   
# the start year and end year
iStart = a_measure_night_complete$YEAR[1]
iEnd   = a_measure_night_complete$YEAR[nrow(a_measure_night_complete)]
# some SWC is missing, so do not trust SWC a lot!
#
# average temperature during growing season
NEE_annual <- a %>% filter(YEAR >= iStart & YEAR <= iEnd) %>% group_by(YEAR) %>% summarise(TA=mean(TA_ERA, na.rm=T), TS=mean(TS_F_MDS_1, na.rm=T), SWC=mean(SWC_F_MDS_1, na.rm=T)) 
NEE_grow   <- a %>% filter(DOY >= gStart & DOY <= gEnd) %>% filter(YEAR >= iStart & YEAR <= iEnd) %>% group_by(YEAR) %>% summarise(TA=mean(TA_ERA, na.rm=T), TS=mean(TS_F_MDS_1, na.rm=T), SWC=mean(SWC_F_MDS_1, na.rm=T)) 
  #
  #
  ac <- a[, c("YEAR", "MONTH", "DAY", "DOY", "HOUR", "MINUTE", "TIMESTAMP")]
  ac$NEE <- a$NEE_VUT_REF
  ac$NEE_QC  <- a$NEE_VUT_REF_QC
  ac$TA  <- a$TA_ERA
  ac$TS  <- a$TS_F_MDS_1
  ac$SWC <- a$SWC_F_MDS_1
  ac$NEE_uStar_f <- a$NEE_VUT_REF
  ac$daytime <- a$NIGHT!=1
  #
# save the ac and a_measure_night_complete data:
data_dir <- '/Users/jw2946/Documents/stability_project/RespiarationData/'
saveRDS(ac, file=paste0(data_dir, name_site, '_ac.RDS'))
saveRDS(a_measure_night_complete, file=paste0(data_dir, name_site, '_nightNEE.RDS'))  
  #
  #
  ac <- a[, c("YEAR", "MONTH", "DAY", "DOY", "HOUR", "MINUTE", "TIMESTAMP")]
  ac$NEE <- a$NEE_VUT_REF
  ac$NEE_QC  <- a$NEE_VUT_REF_QC
  ac$TA  <- a$TA_ERA
  ac$TS  <- a$TS_F_MDS_1
  ac$SWC <- a$SWC_F_MDS_1
  ac$NEE_uStar_f <- a$NEE_VUT_REF
  ac$daytime <- a$NIGHT!=1
  #
# save the ac and a_measure_night_complete data:
data_dir <- '/Users/jw2946/Documents/stability_project/RespiarationData/'
saveRDS(ac, file=paste0(data_dir, name_site, '_ac.RDS'))
saveRDS(a_measure_night_complete, file=paste0(data_dir, name_site, '_nightNEE.RDS'))  

```

```{r try the five models first, fig.width=6, fig.hight=5}
library(gslnls)
library(caret)
library(performance)
#
# put this to a dataframe
data <- data.frame(YEAR=a_measure_night_complete$YEAR,       DOY=a_measure_night_complete$DOY,
                   TA=a_measure_night_complete$TA_ERA,       TS=a_measure_night_complete$TS_F_MDS_1,
                   SWC=a_measure_night_complete$SWC_F_MDS_1, NEE=a_measure_night_complete$NEE_VUT_REF)
#---------------------------------------------------------------------------------------------------------------------
# check data quality first
plot(data$TS, data$NEE)
plot(data$DOY, data$NEE)
#--------------------------------------------------------------------------------------------------------------------
# model 1: linear exponential
frmu   <- NEE ~ C_pool * exp(alpha * TS) * SWC / (Hs + SWC)    # in this formula: C_pool, alpha, beta, and Hs are unclear parameters. I know Cpool and Hs should be positive;
stprm  <- c(C_pool=1, alpha=0.1, Hs = 20) # 
df_accurate <- data.frame(NEE=data$NEE, TS=data$TS, SWC=data$SWC)
# mod1 <-try(nlxb(formula=frmu, start=stprm, data=df_accurate, lower=c(0, -1000, 0), upper=c(1000, -1000, 40)))
# print(mod1)
mod1 <- gsl_nls(fn=frmu, data=df_accurate, start=stprm)
summary(mod1)
NEE_pred <- predict(mod1, newdata=df_accurate)
plot(df_accurate$TS, df_accurate$NEE)
# check performance
postResample(pred=NEE_pred, obs=df_accurate$NEE)
performance_aicc(mod1)
#  RMSE      Rsquared     MAE      aicc
# 2.3256116 0.2067492 1.6912892         (Water is extremely important)
#-----------------------------------------------------------------------------------------------------------
# model 2: quadratic exponential (!the best model!)
# Negative Hs, so I remove the soil moisture effects. 
frmu   <- NEE ~ C_pool * exp(alpha * TS + beta*TS^2) * SWC / (Hs + SWC)     # in this formula: C_pool, alpha, beta, and Hs are unclear parameters. I know Cpool and Hs should be positive;
stprm  <- c(C_pool=10, alpha=0.1, beta=-0.01, Hs = 100) #, Hs = 20
df_accurate <- data.frame(NEE=data$NEE, TS=data$TS, SWC=data$SWC)
mod2 <- gsl_nls(fn=frmu, data=df_accurate, start=stprm)
summary(mod2)
NEE_pred <- predict(mod2, newdata=df_accurate)
plot(df_accurate$TS, df_accurate$NEE)
# check performance
postResample(pred=NEE_pred, obs=df_accurate$NEE)
performance_aicc(mod2)
#    RMSE Rsquared      MAE     aicc
# 2.3006024 0.2188733 1.6639763                  # almost lineaer relationship with SWC
# 
# The best parameter values
# C_pool  0.0855279  0.0245821   3.479 0.000504 ***
# alpha   0.3893684  0.0168435  23.117  < 2e-16 ***
# beta   -0.0061954  0.0003091 -20.045  < 2e-16 ***
# Hs     81.6036440 13.8594544   5.888 3.97e-09 ***
#
#-------------------------------------------------------------------------------------------------------------------
# model 5: Modified Arrhenius  (better than the last; almost the same)
frmu   <- NEE ~ C_pool * exp(- alpha * (1/(15+46.02) - 1/(TS+46.02)))  * SWC / (Hs + SWC)    
stprm  <- c(C_pool = 0.5, alpha = 20, Hs = 20) # 
df_accurate <- data.frame(NEE=data$NEE, TS=data$TS, SWC=data$SWC)
# mod1 <-try(nlxb(formula=frmu, start=stprm, data=df_accurate, lower=c(0, 0, -1000), upper=c(1, 1000, 1000)))
mod5 <- gsl_nls(fn=frmu, data=df_accurate, start=stprm)
summary(mod5)
NEE_pred <- predict(mod5, newdata=df_accurate)
plot(df_accurate$TS, NEE_pred)
# check performance
postResample(pred=NEE_pred, obs=df_accurate$NEE)
performance_aicc(mod5)
#    RMSE Rsquared      MAE   AICc
# 2.3194949 0.2100643 1.6846898 

```
```{r how about predicting for each year using the best model}
library(gslnls)
#
coef <- data.frame(year=double(), C_pool=double(), alpha=double(), beta=double())
perf <- data.frame(year=double(), RMSE=double(), Rsquared=double(), MAE=double())
#
for (i in iStart:iEnd) {     
  data <- a_measure_night_complete %>% filter(YEAR==i)   #
  if (nrow(data) <= 10) {
    next
  }
  print(i)
  #-----------------------------------------------------------------------------------------------------------------------
  # model 2: quadratic exponential (!the best model!)
  Hs = 81.6036440
  frmu   <- NEE ~ C_pool * exp(exp(alpha) * TS + beta*TS^2)  * SWC / (SWC+Hs)    
  stprm  <- c(C_pool=20, alpha=-1, beta=-0.01)            # these initial values need to be adjusted!
  df_accurate <- data.frame(NEE=data$NEE, TS=data$TS, SWC=data$SWC)      
  # mod2 <-try(nlxb(formula=frmu, start=stprm, data=df_accurate, lower=c(0, 0, -1000), upper=c(1000, 1000, 1000)))
  mod2 <- gsl_nls(fn=frmu, data=df_accurate, start=stprm)
  summary(mod2)
  NEE_pred <- predict(mod2, newdata=df_accurate)
  plot(df_accurate$TS, df_accurate$NEE, main=i)
  lines(df_accurate$TS, NEE_pred)
  # check performance
  performance_aicc(mod2)
  coef[i-iStart+1,] <- c(i, coefficients(mod2)[1], exp(coefficients(mod2)[2]), coefficients(mod2)[3])
  perf[i-iStart+1,] <- c(i, postResample(pred=NEE_pred, obs=df_accurate$NEE))  
}

# Remember to check performance before moving on!
# 
coef$Topt  <- - coef$alpha/2/coef$beta
coef$Rpeak <- coef$C_pool * exp(-coef$alpha^2 / 4 / coef$beta)
#
# positive?
# cor.test(coef$Topt, NEE_grow$TA)    # NS
# cor.test(coef$Topt, NEE_grow$TS)    # p-value = 0.02186; positive
# # positive? no? negative?
# cor.test(coef$Rpeak, NEE_grow$TA)    # NS
# cor.test(coef$Rpeak, NEE_grow$TS)    # p-value = 0.01515; positive

# not useful, represent ER at TS=0
cor.test(coef$C_pool, NEE_grow$TS)    # NS
cor.test(coef$C_pool, NEE_grow$TA)    # NS
#
cor.test(coef$alpha, NEE_grow$TS)    # NS
cor.test(coef$alpha, NEE_grow$TA)    # NS
# 
cor.test(coef$beta, NEE_grow$TS)    # NS
cor.test(coef$beta, NEE_grow$TA)    # NS
#
# if correlated to SWC, NO!
cor.test(coef$C_pool, NEE_grow$SWC)    # NS
cor.test(coef$alpha, NEE_grow$SWC)     # NS
cor.test(coef$beta, NEE_grow$SWC)      # NS
#
```

```{r test if there is thermal acclimation}
# strength of thermal acclimation
# T-ER curves of different years
result <- data.frame(TS=double(), NEE=double(), year=integer())
TS    = seq(0, 32, 0.1)
nTS   = length(TS)
nyear = nrow(coef)
for (i in 1:nyear) {
  #
  result[((i-1)*nTS+1):(i*nTS), 3] <- i + iStart - 1
  result[((i-1)*nTS+1):(i*nTS), 1] <- TS
  #
#  if (i==10) {next}
  if (is.na(perf$Rsquared[i])) {
    next
  }
  if (perf$Rsquared[i] < 0.1) {             # I have to remove bad performance years.  
    next
  }
  alpha  = coef$alpha[i]
  beta   = coef$beta[i]
  C_pool = coef$C_pool[i]
  result[((i-1)*nTS+1):(i*nTS), 2] <- C_pool * exp(alpha * TS + beta * TS * TS) * 9 / (9 + 81.6)
}

#
ggplot(result, aes(x=TS, y=NEE, col=as.factor(year))) +
  geom_line() +
  geom_point() +
  geom_vline(xintercept = tStart/10) +
  geom_vline(xintercept = tEnd/10)

# growing season 25-31 C; using a standard method, integration over the period. 
# get the average NEE during the growing season.
result_row <- spread(result, key=year, value=NEE)
# only choose the data with temperature between 11 and 18 C
Ravg_GW    <- colSums(result_row[tStart:tEnd, 2:(nyear+1)]) * 0.1
Ravg_GW    <- Ravg_GW / mean(Ravg_GW, na.rm=T) 

#
# correlation between annual summer temperature and average night respiration at temperature between 2 and 12
cor.test(Ravg_GW, NEE_grow$TS)    # p-value = 0.008677;
cor.test(Ravg_GW, NEE_grow$TA)    # p-value = 0.6459;  
#
# no correlation
df <- data.frame(TS=NEE_grow$TS, alpha = Ravg_GW, SWC=NEE_grow$SWC)
ggplot(df, aes(x=TS, y=alpha)) + 
  geom_point() +
  geom_smooth(method = lm) +
  stat_cor(color='green') + 
  labs(x='Mean soil temperature (C)', y='normalized night respiration under growth temperature')
# linear regression
summary(lm(data=df, alpha~TS))    # slope = -0.21048
summary(lm(data=df, alpha~TS+SWC))

df <- data.frame(TA=NEE_grow$TA, alpha = Ravg_GW, SWC=NEE_grow$SWC)
ggplot(df, aes(x=TA, y=alpha)) + 
  geom_point() +
  geom_smooth(method = lm) +
  stat_cor(color='green') + 
  labs(x='Mean air temperature (C)', y='normalized night respiration under growth temperature')
# linear regression
summary(lm(data=df, alpha~TA))    # slope = 0.1922 

#-----------------------------------------------------------
# how about the relation during growing season?
tmp <- a %>% filter(TS_F_MDS_1 > 2)     # only use the data with TS > 2C
TS_TA <- summary(lm(data=tmp, TS_F_MDS_1~TA_ERA))$coefficients[2,1]
#

# write important results into an output file
outcome <- list(site_ID=name_site, gStart=gStart, gEnd=gEnd, tStart=tStart, tEnd=tEnd, TS_TA=TS_TA,
                NEE_grow=NEE_grow, NEE_annual=NEE_annual, result=result_row, coef=coef, perf=perf)

#
data_dir <- '/Users/jw2946/Documents/stability_project/RespiarationData/'
saveRDS(outcome, file=paste0(data_dir, name_site, '_outcome.RDS'))
# saveRDS(outcome, file=paste0(data_dir, name_site, '_outcome_nowater.RDS'))
```
